---
title: "Research"
output: distill::distill_article
---

### Published

[**The Political Behavior of Family Firms: Evidence from Brazil**](https://www.sciencedirect.com/science/article/abs/pii/S0305750X21003624) (with Pablo Balán and Ignacio Puente). *World Development*, 2022. [PDF](files/WD.pdf). [Online Appendix](files/WD_online_appendix.pdf). [Replication Archive](files/WD_replication.zip). [Shiny App](https://familyfirms.shinyapps.io/contributions/).

### Working Papers

**JOB MARKET PAPER:** [**Inefficient Policies in the Green Transition.**](files/jmp.pdf)

**Family Ties as Corporate Power** (with Pablo Balán and Ignacio Puente). *Conditionally Accepted at the Journal of Politics*. [PDF](https://www.chicagobooth.edu/-/media/research/stigler/pdfs/workingpapers/330bdpstiglerwp.pdf). Media coverage: [ProMarket](https://www.promarket.org/2023/07/24/family-ties-as-corporate-power/).

**An Informational Theory of Coalitional Lobbying.** [Early draft](files/collectivelobby.pdf). [Slides](files/coalitions_presentation.pdf).

**A proof of Blackwell's Theorem for separable metric state spaces.** [PDF](files/blackwell_new.pdf).

### Work in Progress

**The International Politics of Green Industrial Policies.**

**Policy Feedback Effects of Green Subsidies: Evidence from Firm Lobbying after the Inflation Reduction Act.**

**Dynamic Climate Policymaking under Majoritarian and Proportional Electoral Rules.**

**Endogenous Lobbying.**

**Outside Experts as Scapegoats: a Theory of Management Consultants.**

**A New Theory of Partisan Realignment.**


### Old stuff

**Information, Policy Preferences and Voting.** [PDF](files/infoandpolicy.pdf).

**Enchufes, Espejos y Tijeras: Efectos del Diseño de las Boletas Sobre el Comportamiento Electoral** (with Juan Pablo Ruiz Nicolini). *Revista SAAP*, 2017. [PDF](files/Enchufes_espejos_y_tijeras.pdf).

**Spatial Variation in Ecological Inference.** [PDF](files/spatial_eco_inf.pdf).