---
title: "Quine: filosofía del lenguaje"
description: ""
date: 2013-05-31
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

Quine, en *From a logical point of view*, estudia las implicaciones de tomar lo que decimos en una teoría de primer orden.

## Matemática y metamatemática

La idea viene de la matemática. El matemático busca demostrar enunciados en una teoría de primer orden, donde una demostración es una secuencia finita de enunciados que son axiomas o se obtienen de otros enunciados demostrados por ciertas reglas de deducción dadas [nota: para saber qué es una teoría de primer orden, un enunciado, un axioma, una regla de deducción, un modelo, etc., ver un libro de lógica, por ejemplo Lógica de Carlos Ivorra]. Esto se justifica por los teoremas de Gödel: el teorema de completitud de la lógica de primer orden y el primer teorema de incompletitud.

El teorema de completitud dice que un enunciado lógicamente verdadero es lo mismo que un enunciado demostrable. Esto justifica hablar de ‘buscar demostraciones’ en lugar de ‘buscar la verdad (por medio exclusivo de la lógica)’, porque buscar demostraciones (secuencias de enunciados producidas de acuerdo a reglas fijas) es lo mismo que buscar los enunciados lógicos verdaderos (lo cual se entiende como ‘verdaderos en todo modelo de la teoría’).

El primer teorema de incompletitud dice que las teorías que incluyen a los números naturales (léase, que son suficientemente ricas) no pueden ser consistentes y completas (esto quiere decir: todo enunciado es verdadero o falso). Esto justifica que se hable de ‘una teoría de primer orden’ y no de ‘la teoría matemática’. Al matemático le interesa poner reglas de juego explícitas y manejarse exclusivamente dentro de esos límites, cosa que se llama formalización. La lógica permite esto pero impone un límite. Esto justifica que no sea una preocupación que la teoría en la que uno demuestra un teorema sea ‘la teoría correcta’ (sí importa que sea una teoría correcta y suficientemente descriptiva para el fin a mano), porque las teorías no determinan la verdad de todos los enunciados sobre los objetos de los que hablan, es decir, no sirven para definirlos completamente. La matemática nos puede enseñar cosas sobre objetos, pero no nos sirve para definirlos. La matemática no puede decirnos qué es un número, o qué es un conjunto; tenemos que saber de antemano qué es, o trabajar con la teoría sin preocuparnos sobre la verdadera naturaleza de los objetos de los que habla, o incluso sin preocuparnos si habla de ciertos objetos o no. Esto justifica este juego entre ‘adentro’ (matemática) y ‘afuera’ (metamatemática), y que el matemático no demuestre enunciados a secas sino enunciados en una teoría determinada.

Repito: los matemáticos construyen una teoría y demuestran enunciados en esa teoría. Los metamatemáticos estudian estas teorías desde afuera, y pueden mostrar, por ejemplo, que una teoría está ‘contenida’ en otra (en un sentido que definen ellos), que una teoría es consistente si otra teoría lo es, que una teoría es completa, que cierto enunciado en una teoría no es demostrable, o que es demostrable pero sin dar una demostración explícita, etc.; también pueden estudiar las reglas de deducción, comparar unas con otras (lógica de primer orden contra lógica intuicionista o multivaluada o modal), etc. Las demostraciones no son matemáticas, y si bien se podrían formalizar, es decir, construir una teoría que las ‘represente bien’, no podría demostrarse dentro de esa teoría que están bien representadas (ni tiene sentido o utilidad hacerlo).

La ‘referencia’ de los enunciados de una teoría es algo que queda fuera del control de la teoría, si la teoría es suficientemente poderosa. Esto se debe al teorema de incompletitud, ya que si la teoría es consistente, necesariamente hay dos modelos diferentes (con una diferencia expresable en el interior de la teoría). Esto implica que las teorías no definen por completo los objetos sobre los que hablan. Para saber si una teoría habla en efecto sobre ciertos objetos, podemos verificar que hacen un modelo de la teoría (por supuesto desde afuera), es decir, que la teoría no miente sobre ellos, pero no podemos asegurarnos de que no haya otros objetos que también sean descriptos correctamente por la teoría, es decir, que la teoría no sea también una teoría sobre otros objetos. Esto implica que no hay una manera de describir objetos matemáticamente de acuerdo a su significado, es decir, no hay manera de expresar nuestra intención. Con esto quiero decir, incluso si supiéramos responder cualquier pregunta posible sobre un objeto que se siga de su significado solamente, no podríamos capturar esto en una teoría matemática, por más que la teoría contenga infinitos axiomas (e.g. todos los enunciados verdaderos). (Notar que esto debe hacernos dudar de que tenemos intenciones bien definidas cuando buscamos una teoría matemática sobre algo antes que hacernos pensar que la matemática es poco expresiva.)

Otra implicancia de la ‘externalidad’ de la referencia es que podemos hacer matemática sin ella. Podemos saber qué enunciados son verdaderos y qué enunciados son falsos sin ‘saber’ de qué objetos hablan ni qué significan (mientras asumamos consistencia, esto es, que, los conozcamos o no, hay tales objetos). Notar que la alternativa no es muy distinta en definitiva, porque lo más que nos puede ofrecer la metamatemática como descripción de un objeto es otra teoría. La conclusión ‘filosófica’ que se puede extraer de esta observación es, o bien que la indeterminación de la referencia es en definitiva inescapable, o bien que la referencia está determinada desde un principio, y la luz que puede arrojar sobre ella una metateoría no es más que eso: más conocimiento, no conocimiento de diferente tipo, ‘más ontológico’. Notar que la indeterminación de la referencia en un extremo no es más que decir que los objetos matemáticos son abstractos: por ejemplo las palabras, no importa si son un trazo en un papel, píxels en un monitor o electrones en la memoria de una computadora. Cualquiera sea la posición que tomemos, hay que notar que lo que importa, tanto en matemática como en metamatemática, es qué enunciados se pueden deducir de qué enunciados dadas ciertas reglas de inferencia, y no tanto qué cosas existen y qué significan los enunciados.

Un comentario más sobre el peso que debemos darle a la indeterminación de la referencia en las teorías. Notar que hay dos indeterminaciones. La primera, la fuerte, es la que provee el teorema de incompletitud. La otra es que la que se obtiene dando dos modelos diferentes de una teoría que son indistinguibles desde su interior; dicho de otro modo, cuando construimos objetos con las mismas propiedades pero de manera diferente, o hechos de distintos materiales. Pareciera que en metamatemática ‘sí sabemos de qué estamos hablando’, en un sentido no disponible dentro de una teoría. Lo que está mal en este enunciado es la idea de que la metamatemática es algo concreto y fijo, algo distinto de la matemática. Por el contrario, qué es metamatemática y qué es matemática no está dado en principio: se pueden pasar cosas de un lado al otro, por ejemplo, traer números naturales, conjuntos o categorías desde una teoría matemática hacia la metamatemática; y, al revés, formalizar una porción de la metamatemática, volverla una teoría matemática y, por ejemplo, decir cosas sobre ella. La idea de que la metamatemática es la base formada por las construcciones no controversiales (las que no requieren ni prueba ni explicación) es errónea. Hay enunciados metamatemáticos ‘controversiales’, en el sentido de relativos a los axiomas que uno puede aceptar o no, como por ejemplo el teorema de completitud de Gödel, que se sabe que requiere una variante del axioma de elección.

**Resumen.** Matemática es tomar una teoría de primer orden y demostrar enunciados. Si bien demostrar es lo mismo que llegar a la verdad lógica, hay enunciados que ni ellos ni sus negaciones son demostrables, y no se puede dar una definición de la verdad. Por lo tanto tiene sentido considerar varias teorías y estudiarlas desde afuera. Las teorías no determinan los objetos de los que hablan, pero esto no dice más que los objetos son abstractos. Uno puede decir de qué objetos habla una teoría desde una metateoría, pero la metateoría tiene el mismo problema.

Un comentario sobre formalismo y platonismo. Digo que la metamatemática no puede ofrecer más que una teoría cuando trata sobre un objeto. Lo que quiero decir es que no hay ninguna manera de ofrecer, dentro del discurso, una descripción del objeto aprovechable matemáticamente no traducible a una teoría. (Esto es un hecho sociológico, por decirlo de alguna manera, una generalización sobre las características del trabajo de los matemáticos.) Un formalista, un finitista, un intuicionista y un platonista deberían aceptar esto como un hecho, y a partir de ahí, no del todo contentos con esta formulación, podrían discutir sobre cuál es el ‘fundamento último’ de la ‘verdad matemática’. El formalista representaría las afirmaciones matemáticas como afirmaciones sobre los símbolos en el papel; se negaría a aceptar una restricción no matemática sobre la construcción de teorías y estaría preparado para creer que cualquiera teoría es inconsistente. El platonista construiría, por fuera de la matemática, un universo de objetos abstractos, y haría corresponder ciertos objetos matemáticos y sus predicados con éstos y sus propiedades; creería en la consistencia de las teorías y lo atribuiría a la existencia de sus objetos ideales. El finitista descartaría la matemática no finitista (por ejemplo, el teorema de completitud) y se quedaría con el resto; y, de nuevo, creería en la consistencia como consecuencia de la inteligibilidad de las estructuras finitas. Por último, el intuicionista descartaría la regla de tercero excluido de entre las reglas de deducción, y se quedaría con lo que queda. Lo que ninguno puede hacer es, en el medio del discurso matemático, hacer referencia a algo no expresable dentro de la teoría. La matemática se impuso esta restricción en un momento de crisis. El resultado fue que, por medio de una laboriosa e ingeniosa administración de recursos, salió sin registrar pérdidas e, incluso, enriquecida.

## On what there is

Quine estudia las implicaciones de extender esto por fuera de la matemática. Primero, implicaciones ontológicas. Tira la palabra ‘existe’ que no sea el cuantificador (como en ‘las mesas existen’). Luego tira los nombres, usando la teoría russelliana: en lugar de decir ‘Pedro cumple tal predicado’, podemos decir 'existe *x* tal que *EsPedro*(*x*), para todo *y* tal que *EsPedro*(*y*) vale *x* = *y*, y *x* cumple el predicado'; en lugar de decir ‘Pedro no es’, podemos decir 'no existe *x* tal que *EsPedro*(*x*) y para todo *y* tal que *EsPedro*(*y*) vale *x* = *y*'. Entonces, dice, los únicos compromisos ontológicos de la teoría vienen por los enunciados con cuantificadores. Por ejemplo, afirmar ‘existe *x* tal que *P*(*x*)’ nos compromete a aceptar una entidad, y afirmar ‘existe *x* tal que *P*(*x*), existe *x* tal que *Q*(*x*), y, para todo *x*, *P*(*x*) implica no *Q*(*x*)’ nos compromete a aceptar dos entidades.

Ahora bien, los predicados no nos comprometen a nada. Uno podría pensar que nos comprometen a aceptar como entidad su extensión, es decir, el conjunto de los objetos que lo cumplen. O podría pensar que tiene que existir su significación, o su denotación, o su intención, o su idea. Uno puede decir ‘A significa B’ para aclarar su significado, o ‘A y B son sinónimos’, pero no es necesario postular la existencia de una entidad intermedia, la significación de A.

En una discusión ontológica recomienda pasar al plano semántico para evitar la aporía que resulta de hablar sobre las cosas que el contrincante dice que existen para discutirle que en realidad no existen (si uno aceptara hablar sobre esas cosas, estaría admitiéndolas en la ontología propia). Ahora bien, hay teorías con capacidades expresivas similares para ciertos propósitos pero que difieren en su ontología. No hay un criterio ontológico universal —algunas ontologías tienen algunas ventajas y no otras; uno puede usar una u otra ontología según sus fines. Llama esquemas conceptuales a las ontologías (ejemplo, esquema conceptual fisicalista es el que acepta hablar de objetos físicos como mesas, míticos para el esquema conceptual fenomenalista).

## Two dogmas of empiricism

Dos dogmas: distinción entre enunciados analíticos y enunciados sintéticos (viz. verdaderos por significado y verdaderos por los hechos), y reduccionismo (viz. que todo enunciado con sentido es equivalente a alguna construcción lógica basada en términos que refieren a la experiencia inmediata).

Distinción entre nombrar y significar, referencia y denotación, extensión e intensión: ‘el lucero de la tarde’ y ‘el lucero del alba’ nombran lo mismo pero significan cosas distintas. La significación es la esencia de Aristóteles aplicada a la palabra que nombra: es esencial a los hombres ser racionales, pero es accidental tener dos piernas. La significación se puede reducir a la sinonimia, vista como la clase de equivalencia de una expresión. La analiticidad y la sinonimia se pueden reducir entre sí (un enunciado es analítico sii reemplazando los términos por sinónimos llegamos a una verdad lógica; recíprocamente, dos términos son sinónimos sii su reemplazo conserva analiticidad), y lo mismo el modal ‘necesariamente’ (necesariamente p es verdad sii p es analítico). Como éste no está en el lenguaje de primer orden, no hay analiticidad, ni sinonimia. En una teoría de primer orden lo único que hay es referencia, extensión. No hay otra manera de distinguir enunciados o ‘palabras’, así que no hay distinción analítico-sintético.

Verificacionismo: el significado de un enunciado es el método para confirmarlo o refutarlo empíricamente. ‘Persiste la opinión de que con cada enunciado, o con todo enunciado sintético, está asociado un único campo posible de acaecimientos sensoriales, de tal modo que la ocurrencia de uno de ellos añade probabilidad a la verdad del enunciado, y también otro campo único de posibles acaecimientos sensoriales cuya ocurrencia eliminaría aquella probabilidad.’ ‘El dogma reductivista sobrevive en la suposición de que todo enunciado, aislado de sus compañeros, puede tener confirmación o invalidación.’ Notar que esto implica sinonimia: dos enunciados son sinónimos si y sólo si el método de verificación es el mismo, y dos términos son sinónimos si y sólo si son intercambiables en enunciados módulo sinonimia. (Si el resultado de verificar es siempre el mismo, hay además coreferencialidad, que es algo que podría pasar o no.) Y recíprocamente analiticidad implica reducción, porque analiticidad implica poder separar componente semántica de componente empírica. Así que caen el reduccionismo y el verificacionismo también si uno se restringe a teorías de primer orden.

Alternativa: holismo, i.e., las teorías se verifican in toto, y pragmatismo, i.e., cómo uno cambia la teoría en base a la experiencia está dado por los fines. ‘El todo de la ciencia es como un campo de fuerza cuyas condiciones límite da la experiencia. Un conflicto con la experiencia en la periferia da lugar a reajustes en el interior del campo: hay que redistribuir los valores veritativos entre algunos de nuestros enunciados. ... Ninguna experiencia concreta y particular está ligada directamente con un enunciado concreto y particular en el interior del campo, sino que esos ligámenes son indirectos, se establecen a través de consideraciones de equilibrio que afectan al campo como un todo. ... Todo enunciado puede concebirse como valedero en cualquier caso siempre que hagamos reajustes suficientemente drásticos en otras zonas del sistema.’ ‘La ciencia es una prolongación del sentido común que consiste en hinchar la ontología para simplificar la teoría.’ (Esta frase es fascinante. Creo que resume toda la filosofía de Quine.) ‘La cuestión de si hay o no hay clases parece más bien una cuestión relativa al esquema conceptual conveniente. Y la cuestión de si hay casas de ladrillo en Elm Street o la de si hay centauros parecen más bien cuestiones de hecho. Pero he indicado que esta diferencia es sólo de grado.’

Pensar esto con el ejemplo teoría de números racionales vs. teoría de números reales. Los hechos empíricos serían las afirmaciones verdaderas sobre números racionales. Como la teoría de números reales habla sobre números racionales, y en definitiva nos interesa sólo por lo que dice sobre éstos, se justifica el paralelo (una teoría sobre números reales sirve si y sólo si todas las consecuencias sobre números racionales son coherentes con lo que sabemos sobre los mismos; igual que una teoría física serviría si y sólo si todas las consecuencias sobre ‘observables’ fueran coherentes con lo que sabemos sobre los mismos, idea contra la cual está diseñado este argumento). El axioma de completitud de los números reales (que las sucesiones de Cauchy convergen) sería analítico porque es un postulado; en cambio, ‘2 + 2 = 4’ sería sintético porque si los racionales fueran distintos podría no valer. Ahora bien, ver qué consecuencias tiene un enunciado sobre los números racionales depende del resto de los enunciados, y verificar uno es verificar todos. Esto se entiende porque son los mismos axiomas los que ‘definen’ lo que son los números reales: no hay un paso previo. Y qué enunciados tomamos como axiomas está totalmente indeterminado por la teoría (no hay enunciados ‘prioritarios’; el único criterio es que de los enunciados elegidos como axiomas, tomados en conjunto, se puedan deducir todos los demás). Saber lo que significan +, -, <, etc. (como para poder saber qué significa un enunciado a partir de su sintaxis) es equivalente a tener un modelo de la teoría, lo cual está dado por la teoría tomada como un todo, sin posibilidad de discriminar entre las afirmaciones ‘puramente sobre números reales’ y las ‘con consecuencias sobre los números racionales’.

Notar que la filosofía de la ciencia de Quine es absolutamente liberal. (No hay ningún criterio, e.g., el falsacionismo no tiene siquiera sentido para Quine.) Esto es exactamente porque Quine no cree en la filosofía de la ciencia o, en general, en una filosofía primera. Filosofía y ciencia son continuas. Notar, por otra parte, que no hay diferencia a priori entre ciencia formal y ciencia fáctica, ciencia deductiva y ciencia inductiva. También notar que la tesis de indeterminación ontológica ya está: no importa de qué hable la ciencia sino que prediga bien los estímulos nerviosos y sea simple.

En *Identity, ostension and hypostasis*, Quine agrega lo siguiente. Dice que si bien sólo podemos hablar sobre la realidad en términos de nuestro esquema conceptual, podemos modificarlo enteramente. ‘Por eso Neurath ha comparado la tarea del filósofo a la de un marinero que tuviera que reconstruir su barco en altamar.’ ‘Podemos ir mejorando nuestro esquema conceptual, nuestra filosofía, pieza por pieza, mientras seguimos dependiendo de ella porque nos sostiene; pero lo que no podemos hacer es separarnos de ella y compararla objetivamente con la realidad aún no conceptualizada. Afirmo, por tanto, que carece de sentido preguntarse por la corrección absoluta de un esquema conceptual en tanto que espejo de la realidad. Nuestro criterio para apreciar cambios básicos en un esquema conceptual no debe ser un criterio realista de correspondencia con la realidad, sino un criterio pragmático. Los conceptos son lenguaje, y la finalidad de los conceptos y del lenguaje es la eficacia en la comunicación y en la predicción. Tal es el deber último del lenguaje, de la ciencia y de la filosofía, y en relación con ese deber debe apreciarse en última instancia un esquema conceptual.’

Ese párrafo que acabo de citar suena metafísico o epistemológico, como que ‘lo que podemos conocer está limitado por nuestro esquema conceptual’, etc. Entendiéndolo así suena paradójico, porque ¿cómo podemos hablar sobre nuestro esquema conceptual? Tendríamos que hacerlo desde otro esquema conceptual. ¿Cómo hacemos para ‘salir’ y ‘entrar’ de esquemas conceptuales? Parece que hay un fondo cognitivo por fuera de todo esquema conceptual, un escenario donde aparecen y desaparecen de escena los esquemas conceptuales, pero eso es algo que Quine niega explícitamente. Creo que estas preguntas están mal, porque Quine no habla sobre ‘conocimiento’ (así como no habla sobre ‘existencia’ de cosas). Quine habla solamente sobre las teorías de primer orden, diciendo que sólo va a contar como ‘conocimiento válido’ (sobre el cual discutir, argumentar, dar contraejemplos, someter al juicio de la experiencia) aquél así formulado. Quine no habla sobre ‘el origen del conocimiento’ ni cosas así. Él dice: tenemos una vida que nos impone intereses, fines, y ‘conocimientos’ (en un sentido no filosófico), y queremos crear buenas teorías para llevar a cabo dichos fines en base a esos ‘conocimientos’ --- ‘buenas teorías’ es equivalente para Quine a hacer ciencia, meterse en el ‘espacio de las razones’, ser racionales, perseguir la verdad. Ahora bien, si sólo aceptamos teorías de primer orden para nuestro ‘conocimiento científico’, las consecuencias son eliminación del lenguaje intensional, relativización de la ontología e imposibilidad de un reduccionismo empirista. En consecuencia, las preguntas filosóficas sobre ontología y epistemología no tienen cabida. Si Quine tuviera que discutir con, por ejemplo, Descartes, haría lo siguiente. Le enseñaría lógica de primer orden, trataría de convencerlo de que es la mejor manera de expresar los enunciados que quiere sostener, y le diría: ‘estamos en desacuerdo en las cuestiones fundamentales, pero seguro estamos de acuerdo en cuestiones más superficiales, como éstas sobre el lenguaje y la expresividad de la lógica de primer orden; ahora bien, si aceptás esto, nuestro primer desacuerdo se disuelve’. Dicho de otra manera: el argumento en contra de una filosofía primera es un reductio ad absurdum, que va así: si la filosofía es escéptica, entonces es incompatible con la ciencia, lo cual es absurdo; si no es escéptica, en algún momento del desarrollo nos permite hablar sobre teorías de primer orden; los argumentos de Quine empiezan acá, y muestran que lo anterior del desarrollo de la filosofía es completamente irrelevante para nuestras teorías, así que no hay nada que decir sobre eso, o se puede decir cualquier cosa, y da lo mismo; en consecuencia, que haya habido verdaderos argumentos para llegar al punto donde empieza Quine es absurdo. (Ni hace falta decir que esto es un ‘truco sucio’, una petición de principio.) Notar que una epistemología naturalizada se hace perfectamente posible a partir de esta idea (aunque no tendría nada que responder a las preguntas cartesianas).

Otra manera de pensar lo que dije en el párrafo anterior. ¿Qué es lo que está afuera de las teorías? Lo que nos pasa que hace que fabriquemos una teoría y que, llegado el caso, la modifiquemos. Para Quine no es relevante para lo que pasa adentro de las teorías, que es todo lo que nos comprometemos a decir, lo que vamos a contar como conocimiento o como verdad. Lo que queda afuera no interesa. Notar que esta actitud es la contraria a la que tiene Descartes. Las ideas tal como están en la mente, la experiencia pura, etc. Para Descartes son las primeras cosas, las ideas claras y distintas. Para Quine son un misterio, no tienen nada de claras.

## Comentarios sobre el significado y los modales

Una cosa que suele hacer Quine es dado un concepto dar una definición. Por ejemplo la intertraducibilidad entre dos lenguajes se define como el promedio del cociente entre las longitudes de la traducción más corta de una oración y ella misma, sumando sobre todas las oraciones, y tomando el manual de traducción que haga mínimo este número. Esto se justifica porque Quine no cree en el análisis de significados; para él un concepto es la mejor teoría sobre su uso correcto, y no hay ningún test sobre esta teoría por fuera de la utilidad en la comunicación y en la ciencia.

El ‘podría’ de la definición de oración gramaticalmente significativa como ‘oración que podría ser usada sin provocar reacciones que sugieran anormalidades idiomáticas’. Lo que dice Quine es predecible: la lógica de primer orden no acepta el modal así que el ‘podría’ se reemplaza por la teoría más simple coherente con las observaciones: "ese ‘podría’ consiste en sumar lo que *es* y la *simplicidad* de las leyes por las cuales describimos y extrapolamos lo que efectivamente es o hay".
