---
title: "Elecciones estudiantiles en la Facultad de Exactas, UBA, 2015"
description: ""
date: 2015-09-20
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

Se votaron consejeros estudiantiles (obligatorio) y representantes del CECEN (no obligatorio). Votaron 5675 personas para consejo y 2528 para centro (el 44%).

## Resultados

Se esperaba que gane el FEM (la Mella). Arrasó: 44% para consejo, 51% para centro. El segundo puesto estaba peleado entre la Izquierda al Frente (PO + Nuevo MAS + Izquierda Socialista + La Corriente) y Exactas Puede Más (La Cámpora + Nuevo Encuentro + Mov Evita + Seamos Libres). Se lo llevó la izquierda con facilidad: 21% tanto para consejo como para centro, quedándose con el consejero de la minoría. EPM sacó 16% para consejo y lo mismo para centro. Las dos listas restantes, Cambio de Base (Bandera Negra, anarquistas) y Nuevo Espacio (reformistas), fueron irrelevantes.

## FEM

El FEM hizo una elección notable. Tanto en comparación con años anteriores (27% en 2013, 35% en 2014) como en comparación con otras facultades (se profundizó la caída de la Mella en todas excepto Exactas, Psicología y -por aliarse al ganador- Fadu). Es récord histórico: sólo se puede comparar con la elección de 2011 (43% para consejo, 46% para centro). Esto se explica por los siguientes motivos: 1) una buena gestión, 2) un uso racional de los recursos de poder, 3) la homogeneidad y presencia visible en espacios académicos de su base militante, y 4) el apoyo de los estudiantes a su tratamiento del conflicto presupuestario.

### Gestión

El FEM conducía el centro, y por lo tanto contó con la ventaja de ser oficialismo. Esto rindió electoralmente por su buena gestión. El CECEN amplió y mejoró espacios públicos y servicios (nuevo bar, mejoras en la biblioteca Noriega y el sum, desayuno y merienda baratos). Funcionó como herramienta gremial en los conflictos que surgieron (CBC, Tecnópolis, Becas Bicentenario, presupuesto). Tuvo una buena política de comunicación (carteles, presencia en redes sociales, asambleas). Y ofreció espacios de participación a los estudiantes (comisiones de carrera, comisiones del CECEN) que alcanzaron el objetivo mínimo de llevar a cabo actividades abiertas. En resumen: hizo bien lo que debe hacer un centro de estudiantes. Lo cual no es poco, dada la pésima gestión de la Izquierda al Frente en 2014.

### Manejo de recursos de poder

Los logros de gestión en el CECEN fueron capitalizados políticamente por el FEM. La estrategia para conseguir esto no fue la obvia (ponerle el sello de la agrupación a todo). Se apostó al CECEN como vehículo de acción política jugando inteligentemente con sus límites. Se invirtieron los recursos de poder racionalmente: el CECEN se expandió donde fue más redituable para el FEM y se detuvo o retrocedió en los terrenos más adversos, menos rendidores o más riesgosos.

El FEM apostó al fortalecimiento y ampliación institucional del CECEN. Durante el año hizo sus campañas a través del centro sin la firma FEM. Con esto marcó la cancha a las demás agrupaciones: usó la legitimidad que da el sello CECEN para imponer los términos de la discusión pública (el mejor ejemplo: instalar el hashtag #DefendamosExactas). Al mismo tiempo amplió los espacios de representación: impulsó actividades desde las comisiones de carrera que saturaron esa agenda y cooptaron voluntades no partidarias.

Pero así como el CECEN se expandió en espacios de participación bajo la conducción hegemónica del FEM, en otros espacios mostró nula iniciativa o incluso retrocesos por tensiones con otros actores que no quiso o no pudo resolver. Hubo tensiones con los "becarios": trabajadores de las fotocopiadoras y kioskos del centro, que -¿sorprende a alguien?- están en negro y ganan poco. Algunos de ellos son independientes u opositores, y les costaron la elección de centro en 2013. El FEM a principio de este año intentó echar a una administradora no partidaria y hacer electivos esos cargos para asegurarse el control de ese espacio de poder. Intentó justificarlo públicamente y falló.

También hubo tensiones con las otras agrupaciones, cansadas de que les roben proyectos o campañas. Y con las autoridades y los consejeros de otros claustros: si bien hubo un diálogo fluido, el FEM no dudó en traicionarlos y jugar su propio juego cuando le resultó conveniente (reunirse con el rector Barbieri por el conflicto presupuestario a espaldas de las autoridades de la facultad). Lo cual tiene como costo el debilitamiento de su posición en el consejo directivo para avanzar proyectos a escala superior a la del CECEN. Por último, el FEM convive con una tensión con la institucionalidad misma del centro: el CECEN no tiene estatuto ni personería jurídica. El FEM calcula que la dificultad y el costo de llevar adelante estas reformas superan los posibles beneficios.

### Homogeneidad y presencia

El FEM no es una alianza política. No tiene facciones ni se observan grandes diferencias internas. Si bien proclama que tiene una clase de militantes diferenciada, los "independientes" (no orgánicos a la afiliación partidaria en Patria Grande), lo que hay es un gris de organicidad o adhesión ideológica que es común a cualquier agrupación política. Los militantes entran siendo "independientes" y van siendo persuadidos y formados gradualmente en la línea política. Hay -eso sí- flexibilidad y se incorporan nuevas ideas, las que mejor se adaptan a la sensibilidad de los estudiantes de la facultad. Pero la acción es coordinada y todos los éxitos son capitalizados por la organización.

El FEM está resistiendo un recambio generacional. Pero no sólo no presenta grandes peligros en el corto plazo sino que constituye un activo, en tanto muchos veteranos permanecen en la facultad como docentes o investigadores y aportan su ayuda desde ese lugar. Esta presencia en espacios académicos se suma a la de la propia base militante estudiantil: el FEM tiene "codepers" en las comisiones departamentales (y si no los tiene intenta cooptarlos), y varios de sus miembros son ayudantes en materias de sus carreras.

### Conflicto por el presupuesto

Además de contar con estas tres ventajas frente a la competencia, el FEM protagonizó este año una campaña que entiendo que fue decisiva para el resultado electoral. Se trató de la campaña por más presupuesto para la Facultad. El FEM la condujo desde el movimiento estudiantil, fijó el significante (la etiqueta) con el que todos los actores la nombraron (el hashtag #DefendamosExactas, en clara imitación de #NiUnaMenos), estableció una narrativa que tuvo aceptación incluso entre la oposición de izquierda, y obtuvo una "victoria" controvertida pero validada como tal por una amplia mayoría de estudiantes.

Resumo la historia. A principio de año el decano Reboreda anunció que con el presupuesto que le asignó el Consejo Superior para 2015 Exactas "no llega a Octubre". El presupuesto de la UBA se reparte así: se destina lo necesario para el pago de salarios, y el resto se destina entre administración central (Rectorado), facultades y hospitales para "gastos de funcionamiento". El presupuesto para facultades, a su vez, se reparte entre las trece. Está en discusión qué porcentaje le debería tocar a cada una. Hasta hace unos años, gracias la gestión del ex decano Jorge Aliaga, la repartición se hacía de acuerdo a un criterio que tenía en cuenta el tamaño y la complejidad de cada facultad. Exactas es pequeña demográficamente, pero sus laboratorios y sus tres edificios la hacen merecedora de entre 13 y 15% del presupuesto de acuerdo a ese criterio, muy por encima del promedio que, por ser 13 facultades, está en 7.7%. Exactas perdió el lugar político que tenía en esos años en el CS, lo cual recrudeció tras la elección del rector Barbieri en 2013, apoyado por casi todos los decanos pero no por el de Exactas. Por este motivo la porción del presupuesto que le asigna el CS viene cayendo desde ese momento, tendiendo al 10%, a lo cual se suma que por ser opositora al rector no recibe fondos discrecionales extra. Exactas tenía ahorros que fue gastando en este último tiempo, pero se terminaron el año pasado. Por eso este año el decano anunció la situación de emergencia presupuestaria.

El decano lo anunció a toda la comunidad académica. El FEM reaccionó rápidamente poniéndose al hombro, a través del CECEN, la tarea de pelear por más presupuesto entendida como un reclamo estudiantil bajo la consigna "#DefendamosExactas". Desde el primer momento hubo comunicación entre el FEM y las autoridades pero también desacuerdos en los métodos de presión. Las autoridades buscaban canalizar el reclamo por vía institucional dentro del CS, lo cual terminó en un fracaso rotundo (una primera propuesta de reasignación de una partida presupuestaria ni se trató en la comisión correspondiente del CS; una segunda, que llamaba a repartir una partida nueva con una variante del criterio que beneficiaba a Exactas fue rechazada incluso por el representante de la Mella en el claustro estudiantil). El FEM, en cambio, fue al choque: desde el CECEN colgó una bandera gigante con la consigna #DefendamosExactas y reunió a buena parte de la facultad en una foto, y organizó asambleas y movilizaciones al Rectorado desde el primer momento. Es altamente cuestionable que esto haya tenido algún impacto real en las decisiones del Rector. Estoy convencido de que no lo tuvo, pero entiendo que una mayoría de estudiantes creyó que sí. Y que tanto la instalación del conflicto en la agenda de los estudiantes como del relato de victoria fueron validados por los votantes y fueron determinantes en la elección.

La "victoria" que se atribuye el FEM se dio como sigue. Lucas Tavolaro, militante del FEM y tesorero del CECEN, participó en la competencia de programación mundial ICPC como parte del equipo que representó a la UBA. Su equipo obtuvo un buen resultado, posicionándose en el ranking global como el mejor de Latinoamérica. Pero lo que llamó la atención de los medios locales no fue eso, sino un resultado anecdótico pero simbólicamente fuerte: la UBA le ganó a Harvard. Así lo editaron los medios, que por ese motivo entrevistaron a Tavolaro. Tavolaro aprovechó la cobertura mediática en diarios, programas de TV y radio para pedir más presupuesto para la Facultad. El rector Barbieri, muy atento a su imagen mediática, respondió al poco tiempo. El Ministerio de Educación le estaba girando a la UBA una partida presupuestaria extra de $20 millones (como pudimos reconstruir más tarde), seguramente no relacionada de ningún modo con el conflicto de Exactas. Barbieri se reunió con Tavolaro y Galpern, presidente del CECEN, en su oficina, a solas, para anunciarles la primicia de que iba a destinar $15 millones extra para gastos de funcionamiento a repartir entre las facultades (usando, por supuesto, el criterio que perjudica a Exactas, otorgándole un 10% de ese dinero). El FEM definió esto como una victoria estudiantil, e instaló el relato de que fue una conquista de todos los estudiantes organizados y movilizados por... ellos, el FEM. El consejo directivo de Exactas, sin embargo, no lo vio de esta manera: al legitimar desde la "izquierda" estudiantil la repartición de los $15 millones, el FEM hizo que se debilite el reclamo de Exactas en el CS, dejándola en una posición política aún más precaria que la que tenía. El éxito del FEM en 2015 puede significar el fracaso de Exactas del 2016 en adelante. Y de los $5 millones de esa partida de $20 millones que recibió Barbieri y que no repartió entre las facultades nunca se supo nada, ni se hizo ningún reclamo. El triunfalismo no dejó lugar para esos detalles.

### Cómo traducir un conflicto en hegemonía electoral

No es la primera vez que el FEM lleva a cabo una campaña con este éxito. En 2010 organizó desde el CECEN (junto a AGD, gremio docente de izquierda) un plebiscito entre estudiantes, docentes y graduados que planteaba una pregunta: acreditar las carreras de grado en la CONEAU, sí o no. Un 92% votó que no. Junto a esto se confeccionó y colgó una bandera gigante con la leyenda “en Exactas no acreditamos”. El CECEN conducido por el FEM organizó asambleas y movilizaciones para defender esa posición. El resultado fue un éxito: si bien se acreditaron doctorados y maestrías, las carreras de grado continúan hasta hoy sin acreditar. Y el FEM cosechó resultados frondosos en las elecciones siguientes. Hay elementos en común con el conflicto por el presupuesto de este año de los que puede extraerse un patrón. 1) La instalación de un tema en la agenda estudiantil durante todo el año, más el esfuerzo por no perder la atención de los estudiantes en ningún momento. 2) El interesamiento de los demás actores académicos en la consigna, manteniendo un margen de autonomía siempre. 3) El uso del CECEN como vehículo exclusivo de organización estudiantil legítima. Y 4) el monopolio de los símbolos (la bandera gigante, la consigna simple: acreditar sí/no, #DefendamosExactas). Esto deja planteada una pregunta: ¿podemos detectar este mismo patrón en hechos políticos exitosos de la política estudiantil democrática en otras facultades?

## La Izquierda al Frente

La Izquierda al Frente (la izquierda, de ahora en más) salió segunda con el 21% de los votos tanto para centro como para consejo. Consiguió, así, el consejero por la minoría, peleado con el frente kirchnerista Exactas Puede Más. Pero no es para festejar: la izquierda en Exactas está en una decadencia sostenida. Obtuvo 24% el año pasado y ganó el centro con 30% en 2013. La Corriente (maoístas) está agonizando. Y el PTS ni siquiera perdió tiempo en presentarse. Prefirió invertirlo en dividir el voto de izquierda en FADU para que el PRO gane el centro. Y ni siquiera eso logró. La izquierda en Exactas está con vida gracias al PO -mayormente-, al Nuevo MAS y a IS.

La campaña del PO se orientó a hacer reclamos y denuncias. Reclamos por más presupuesto, más becas, más y mejores laboratorios, mejoras edilicias, mejoras laborales para los trabajadores en Tecnópolis. Y denuncias de convenios con empresas privadas: Papel Prensa y Pan American Energy.

El PO tiene presencia en espacios en donde se toman decisiones (el consejo directivo, pero no sólo ahí). Y una manera de procesar los conflictos de intereses híper eficiente: si hay que discutir cómo asignamos recursos escasos (difícil), decimos que no son suficientes y que hay que exigir más (fácil); si hay que discutir las condiciones de un convenio con un privado (difícil), decimos que hay que rechazarlo de plano ya que todo convenio es privatista y lleva a la mercantilización de la educación (fácil). De esta manera el PO puede mantener una línea discursiva activa y coherente en el tiempo con un costo muy bajo. Donde hay un conflicto el PO está, de manera visible y defendiendo banderas atractivas para los estudiantes. Pero jamás lo veremos impulsando discusiones profundas con capacidad transformadora. Su desempeño electoral depende más que nada de su buen manejo de la comunicación, de la conservación y reproducción de su base militante, y de que haya algo por lo que reclamar.

El Nuevo MAS en su campaña promocionó enfrentamientos. Los enemigos: el ajuste, el estatuto universitario, los convenios con privados, los comedores, el patriarcado y el capitalismo. Aprovechó para hacer campaña por el MAS y Las Rojas. Izquierda Socialista hizo una campaña similar, con un énfasis también en la lucha feminista.

Se pide el voto para que el representante, de ser elegido, luche. Pero no se hacen explícitos planes de lucha concretos en los que el movimiento estudiantil con los recursos institucionales que se ponen en juego en la elección tome la iniciativa. Hagamos asambleas, emitamos declaraciones, pintemos carteles, marchemos a rectorado, tomemos la facultad. Los instrumentos son específicos, pero los objetivos no. Y la capacidad de articular voluntades para acumular poder real se muestra limitada. Ofrecen más una vidriera del activismo más o menos real que se da afuera de la facultad que un proyecto creíble de lucha desde el interior. Sus votantes son simpatizantes, adherentes de sus causas. No hacen una apuesta política.

## Exactas Puede Más

Las tres agrupaciones kirchneristas (La Cámpora, Nuevo Encuentro y Mov Evita) se unieron en un frente político, Exactas Puede Más, que además incorporó a Seamos Libres. El año pasado los K fueron a elecciones en una lista única, pero con campañas diferenciadas. Seamos Libre se presentó aparte. La lista K obtuvo el 15% de los votos. Seamos Libres, el 6%. Este año obtuvieron juntos el 16%. Se puede computar como un retroceso: no lograron siquiera sumar los votos del año pasado. El objetivo era crecer y superar a la izquierda. No lo alcanzaron.

La lista K venía de crecer 6% entre 2013 (obtuvo el 9%) y 2014 (15%). Sus militantes proyectaban un nuevo crecimiento del 6% para este año, que no se dio. Era verosímil: no por la extrapolación lineal que proponían sino porque ese 6% lo podían aportar los votantes de Seamos Libres, que se sumó al frente. Pero quizás lo que haya que explicar no sea la caída (o el estancamiento) del kirchnerismo en 2015, sino el crecimiento en 2014. Lo primero se explica fácil. La excelente elección del FEM hizo que fuera un año inusualmente difícil para la oposición. Y la izquierda demostró que tiene una base de apoyo sólida y una capacidad de llegada a los estudiantes que resiste.

Lo segundo también tiene explicación: en 2014 la izquierda venía de hacer una pésima gestión del CECEN, lo que abría las puertas a la oposición. Y era el año de llegada a la facultad de Nuevo Encuentro, que conectó con los estudiantes con campañas basadas en acciones reales sin el aparato del CECEN o el voto en el consejo (filmación de teóricas, cursos de portugués, un festival, militancia por un menú de desayuno y merienda). A lo que contribuyó una buena comunicación (con recursos innovadores y el carisma de su representante).

Este año, en cambio, Nuevo Encuentro se deslució. Buscó renovar y consolidar la organización hacia su interior, dejando de lado las campañas gremiales que le habían ganado el reconocimiento de los votos el año pasado. La Cámpora, contando con un liderazgo renovado a nivel UBA, apostó a seguir el camino que marcó NE en 2014. Con aciertos y algunos desaciertos se hizo más visible e hizo crecer su base militante. Lo cual quizás explique que en el contexto desfavorable no haya retrocedido tanto su voto.

EPM buscó pelearle a la izquierda el consejero de la minoría con la consigna "pluralidad de voces". La izquierda tuvo razón en burlarse: el consejo tiene mayoría kirchnerista (tanto en graduados como en profesores); sumar kirchnerismo no iba a hacer crecer la pluralidad. Pero, por esa misma razón, la apuesta política a la que llamó EPM fue la más sustancial.

El FEM llamaba a validar su buena gestión del CECEN y su conducción de los conflictos gremiales. La izquierda llamaba a validar sus reclamos y sus luchas. EPM, en cambio, hizo una campaña propositiva, sin referencias partidarias. "Imaginate todo lo que podemos hacer", fue el slogan. Resulta difícil imaginar el éxito de todas las propuestas que hicieron en su plataforma, incluso en un escenario hipotético de ser mayoría tanto en el CECEN como en el CD. Pero fueron los únicos que hicieron un planteo político transformador y hasta cierto punto creíble. Propusieron reformas académicas necesarias pero políticamente costosas, que requerirían un enorme trabajo y grandes consensos (una revisión del plan de estudios de biología y títulos intermedios para todas las carreras).

Exactas es una facultad que produce investigación, más básica que aplicada. Pero tiene un enorme potencial para contribuir al proceso de desarrollo del país. Lograr eso requiere de una discusión profunda y de cambios de conducta y de valores por parte de todos los actores que la integran. El kirchnerismo, con su retórica y su política de promoción de la ciencia y la tecnología como sectores estratégicos, provee un fondo sobre el cual llevar adelante estas reformas. Hay, con esto, una oportunidad para que la política universitaria transforme significativamente su realidad, empoderando a los estudiantes en ese proceso. Lo cual tendría la chance de alcanzar un resultado muy distinto al caso paradigmático de la facultad de Económicas, que sí logró atravesar un proceso de gran transformación. Pero que, siendo un éxito de la política democrática, fue un fracaso para los valores que defienden los estudiantes de Exactas (Económicas consiguió su autonomía económica a cambio de su apertura al mercado, y logró cambios en sus planes de estudio a costa de multiplicar los posgrados arancelados). Hay, por lo tanto, una oportunidad pero también un enorme riesgo.

Frente a este escenario la izquierda es conservadora. Tiene motivos ideológicos y prácticos para esto. En contraposición el kirchnerismo hace una apuesta arriesgada. Pero por ahora no despega. Frente el FEM tiene dos grandes desventajas. Los militantes del FEM están organizados en un espacio político coherente y durable, conocen el funcionamiento de la facultad desde adentro y son conocidos en los espacios en los que participan. Los militantes de EPM, en cambio, están distribuidos en cuatro espacios políticos que tienen sus propias identidades, que no están consolidados hacia adentro ni consolidaron una organización que les permita actuar compartiendo recursos y beneficios. La segunda ventaja del FEM está en que logró imponer su versión de los hechos en torno al conflicto por el presupuesto. EPM vindicó el reclamo estudiantil que condujo el FEM pero cuestionó la victoria. El FEM le ganó la batalla por la credibilidad, poniendo así a EPM en una posición impopular y reaccionaria.

La victoria del kirchnerismo en Sociales se podría haber replicado en Exactas. Leandro Germán, un militante del PO, en un análisis muy interesante hace un listado de las condiciones que hicieron eso posible. Resumo: 1) Sociales está ligada institucional e ideológicamente al kirchnerismo (sociología a Carta Abierta, comunicación a la "ley de medios", ciencia política a la "reforma política" del 2009, trabajo social a la AUH, relaciones del trabajo al Ministerio de Trabajo), 2) hay una mayoría kirchnerista en docentes, 3) el centro de estudiantes viene de ser conducido por La Mella (entre 2008 y 2013), una izquierda que no es abiertamente antikirchnerista, y 4) viene de una mala gestión de la izquierda. Las primeras tres condiciones se repiten en Exactas: 1) Exactas tiene un vínculo con el kirchnerismo en la repatriación de científicos y la creación del Ministerio de Ciencia, 2) tiene mayoría kirchnerista en docentes, y 3) La Mella conduce el centro de estudiantes. Hay una gran diferencia: la Mella se repuso a la crisis del 2013 en Exactas. En Sociales no. La pregunta que queda abierta es por qué.

## Fuentes

* [Juventud Informada](http://www.juventudinformada.com.ar/).

* Max Pérez Fallik, [El “No a la CONEAU” en la Facultad de Ciencias Exactas y Naturales de la Universidad de Buenos Aires: rupturas y continuidades](http://jornadasdesociologia2015.sociales.uba.ar/wp-content/uploads/ponencias/1707_141.pdf).

* Leandro Germán, [análisis de la elección en Sociales](https://www.facebook.com/leandro.german.10/posts/10205785886543289).
