---
title: "Comentario sobre Harman"
date: 2015-11-26
date-format: "MMMM D, YYYY"
canonical-url: "https://juandodyk.github.io/posts/2015-11-26-comentario-sobre-harman/"
---

::: {lang="es"}
Comentario sobre el texto “Descubrir objetos nuevos es más importante que eliminar objetos viejos”, de Graham Harman.[^1]

## 1. Puesta en escena. Latour, irreduccionismo, y reduccionismo hacia arriba

En la primera parte Harman dice esto, en resumen. Latour en su libro Irreducciones se plantea la tarea de hacer una filosofía que evite todo reduccionismo. Harman se pregunta si lo consigue realmente. Hay dos objeciones a la estrategia de Latour. La primera es mayormente obvia, inevitable e inofensiva. Latour propone ver a toda entidad, para evitar aplastarla con presupuestos a priori, como un agente sin ninguna propiedad determinante (interna), y por lo tanto completamente libre en principio; su realidad no pasa por su esencia o su existencia (reconoce gradientes de existencia por los que puede pasar una entidad) sino por su acción, que siempre involucra a otros agentes y produce un desplazamiento de roles por el proceso que Latour llama traducción. La objeción es: esto también es un molde a priori con el que tratar a todas las entidades de la misma manera. Harman dice: sí, pero toda teorización metafísica está condenada a esto. El mérito de la propuesta de Latour está en que si bien todo es un actor, ningún actor (en principio) está reducido a ningún otro. Algo para notar es que Latour sí admite la reducción; el truco es que no es “el analista” (así hablan los sociólgos) el que reduce, sino los agentes mismos los que operan reducción cuando lo consiguen (y nunca es definitivo). Lo que propone Latour es que no sea la teoría la que reduce, que es, por supuesto, todo a lo que se puede aspirar desde la teoría misma. Entonces esta primera objeción llama a cuestionarse qué esperar y qué no de un antirreduccionismo radical como el de Latour, pero no invalida el suyo.

Hay una segunda objeción que sí es más dañina, y alrededor de la cual gira el argumento de Harman. Latour busca evitar un reduccionismo hacia abajo: el de un objeto que “no es más que” ciertos objetos más fundamentales, el de una predicación que “no es más que” la determinación de una propiedad esencial, o el de un evento que “no es más que” la consecuencia de una ley causal. Entonces Latour prohibe a la teoría elegir sus entidades fundamentales favoritas (y de esa manera, por ejemplo, bloquea desde el vamos el debate realismo vs nominalismo), prohibe el esencialismo y la noción de sustancia, y propone reemplazar la explicación causal por descripción en términos de acción. Negadas estas salidas comunes propone ver toda entidad como un agente en principio libre, todo evento como acción bajo el modelo de la traducción, en el que dos o más agentes se combinan para formas un tercero que los coordina, y toda propiedad en términos de estos efectos relacionales. Harman objeta: si no hay más orden que el que aparece con la coordinación de actores bajo el mando de uno nuevo, es decir, si toda propiedad es relacional, lo único que hizo Latour fue cambiar un reduccionismo hacia abajo por un reduccionismo hacia arriba. La primera apuesta de Harman es introducir la posibilidad de este otro reduccionismo del que también habría que liberarse (al menos si uno busca liberarse del reduccionismo en general siguiendo a Latour). Latour se habría quedado a mitad de camino, apuesta Harman. Él nos va a enseñar finalmente cómo ser irreduccionistas tout court.[^2]

## 2. El argumento central: contra los dos tipos de reduccionismo

La segunda parte del texto se dedica a establecer estos dos tipos de reducción: hacia abajo y hacia arriba, que el llama, respectivamente, socavamiento y disolución. Traza una génesis de estos dos modos de la metafísica y los postula ubicuos: nadie antes logró liberarse de ambos. El cientismo cae más en el socavamiento, pero las humanidades caen igualmente en la disolución. Seguido hace la observación que hice con respecto a la primera objeción contra Latour: no es que esté mal socavar o disolver, sólo que no puede ser un objetivo primordial y sistemático, como si de eso se tratara relacionarse bien con el mundo (la idea de la ilustración). Y acá viene lo que yo creo que es el argumento central del texto, que es por qué o en qué cree Harman que fallan generalmente los dos tipos de reducciones. Antes de hacer un comentario voy a repasar también estos argumentos. Hago esto, en lugar de lanzar mis críticas directamente, porque no uso el mismo vocabulario que Harman, entonces para poder conversar tengo necesariamente que traducirlo; y no voy a dejar de ser latouriano justo acá como para creer que no opera ninguna transformación cuando hago esto.

El argumento anti socavamiento dice que éste va contra la “emergencia”. Este es un concepto viejo, que si yo no entiendo mal Latour elige evitar, y que incluso ataca. Está asociado a la “complejidad” y a los “sistemas”, a Prigogine, a Deleuze y a Luhmann. Argumentos en contra a los que adhiero se encuentran en Latour y Strum, Redefining the social link. Todos los ejemplos que da Harman de emergentes pueden entenderse en otros términos. Sus objetos emergentes se arreglan incluyendo la dimensión del tiempo (que por algún motivo se cuidad de no tocar jamás, como si fuera sagrada). Por ejemplo, “un cuerpo sigue siendo el mismo si le es sustraído un cierto número de células”. Sí, es cierto, pero nada impide reducir al cuerpo no a un conjunto de células sino a un cierto conjunto de células-tiempo (entre t0 y t1 a tales células, entre t1 y t2 a tales otras, etc); no digo que esto no tenga problemas, pero no es vulnerable a la objeción de Harman, y no queda claro que de esta manera (más o menos ad hoc) no se pueda evitar sistemáticamente todo contraejemplo de este tipo. Esto ya lo decía Carnap hace quizás 100 años; Quine es un ejemplo de filósofo que lo sostuvo hasta sus últimas consecuencias, con el máximo de reducción posible. Sobre las propiedades emergentes que cita hay un problema epistémico: que tengamos evidencia incompleta o sólo tengamos leyes cualitativas o estadísticas no quiere decir que el fenómeno no esté determinado por sus partes. Puede ser imposible una reducción nomológica, de leyes de un tipo a leyes de otro tipo, pero eso no es motivo suficiente para bloquear toda reducción ontológica. (Ejemplo, Davidson en Anomalous monism: se puede ser monista ontológico, es decir, no creer que existe el alma, y creer sin embargo que las leyes físicas no pueden bastar para fijar el contenido de nuestros conceptos semánticos.)[^3]

Cuando argumenta en contra de la disolución Harman cae en el mismo problema en el que parece atrapado: el tiempo para él es sagrado, no se toca. La ontología está separada del tiempo, para él. Alguien que sepa de Heidegger quizás pueda sugerir por qué no deja de aferrarse a esta creencia (quizás él mismo), pero en cualquier caso creo que adoptar esta postura sin ningún argumento es motivo suficiente para rechazar la propuesta que hace en su texto. Quizás para él sea obvio, pero para mí que en este momento sólo tengo presente este texto suyo no. La crítica a la disolución que hace, si funcionara, recaería de lleno en la teoría del actor-red de Latour, con efectos quizás fatales. Como funciona la traducción, un actor traducido no tendría manera de zafarse de una red más que siendo traducido por otro actor, y por lo tanto quedaría maniatado por su traductor. Finalmente no serían tan libres los agentes de Latour como éste se propuso una vez lanzados al mundo. Pero eso es porque Harman ignora otra vez la dimensión del tiempo: para Latour ninguna traducción es definitiva. Todo actor-red puede colapsar y descomponerse en un conjunto de actores con metas divergentes. Un auto puede funcionar bajo el mando del conductor lego como auto por un buen tiempo, hasta romperse y convertirse en un empaquetado heterogéneo de partes cada una de las cuales responde únicamente a un especialista propio. La disolución es una restricción a la libertad o autonomía pero no es esencial ni definitiva, y es en esto en lo que radica el mérito de la teoría de Latour. Por los argumentos que da Harman no queda claro que la segunda objeción (en los términos de la primera parte de este texto) sea más dañina que la primera. Esto es el centro de la argumentación de Harman, y creo que expuse motivos suficientes para rechazarla.

## 3. La propuesta de Harman

A pesar de que rechacé su argumento central, del que depende el resto, quiero repasar lo que propone. Podría arguirse: la propuesta es buena, solo que necesita un mejor abogado. Yo creo que no: los problemas que tienen los argumentos antirreduccionistas se reproducen en la propuesta de la sección 3. Y de hecho yo estoy de acuerdo en gran medida con el ánimo antirreduccionista de Harman. Es la calidad de la argumentación y sus recursos con los que tengo problemas, y hacia dónde hacen dirigir a su ejecutor.

Habla mal de los “métodos intelectuales”. Yo estoy en contra de la “metodología” y la filosofía me acompaña hace unas cuantas décadas en esto. Queda sin efecto el llamado de Harman a abandonar algo que ya fue abandonado hace mucho. Es llamativo igual lo que propone en cambio, los “contramétodos”. Lo primero que noto es que Harman no está dispuesto a señalar o definir los contramétodos explícitamente. La fuerza de su propuesta radica antes en convencernos de que tiene que haber algo más que los métodos, en señalar ese espacio vacío. Algo tiene que haber además de los métodos: esa es la apuesta, no una descripción explícita de un candidato. Pero ¿tenemos que creer esto? Yo no creo ni que tenga que haber “métodos” intelectuales ni mucho menos estos “contramétodos” misteriosos. Los ejemplos que delinea oblicuamente no ayudan a convencerme. El argumento sobre la “alusión” y el bosón de Higgs es una simplificación tonta de los argumentos de Kripke y Putnam sobre los nombres de tipos naturales.[^4] A continuación tira esta frase: “Para llegar hasta la naturaleza oculta de las cosas, la oblicuidad y la metáfora son herramientas más precisas que cualquier catálogo engreído, despreciativo y reduccionista de sus rasgos palpables.” Yo me pregunto: ¿quién quiere llegar hasta la “naturaleza oculta de las cosas”? ¿Qué es eso? ¿Cómo tiene sentido pedir herramientas “precisas” para llegar a una naturaleza “oculta”? Si la naturaleza es oculta a priori ¿tiene sentido buscar herramientas para llegar a ella? Harman tiene una tendencia contradictoria: por un lado nos llama a dejar libres a los objetos, no encarcelarlos asignándoles una naturaleza que los determina de una vez y para siempre; por otro lado nos llama a buscar “contramétodos” para acceder a esa misma naturaleza que nos llama a rechazar. Es profundamente incoherente su propuesta. Notar que podemos, de nuevo, detectar el fantasma de Heidegger dando vueltas acá, como justificación posible de estas movidas aparentemente irracionales. Pero hay que recordar el desarrollo de las ideas de Heidegger: del pragmatismo de El ser y el tiempo a la autofagia del lenguaje y de toda comunicación intelectual en su último período. Claro que El Ser queda afuera de los “métodos”, pero ninguna propuesta va a reparar esto. En tanto intenta proponer algo, en tanto cree que hay algo, alguna cosa, que poner en lugar de los “métodos”, la posición de Harman es incoherente.

Después se defiende de dos objeciones. La primera es una versión del verificacionismo. El verificacionismo se viene combatiendo en filosofía analítica desde el año 1950 o antes, por ejemplo en Quine, Two dogmas of empiricism, en el que ataca también cierta forma de reduccionismo. Si lo único que tiene para decir Harman es esto, ya lo viene diciendo Quine hace 60 años. Llegó tarde.

Después dice que el esencialismo es la pretensión de que podemos conocer las esencias. Esto es falso. Hay esencialismo epistémico y esencialismo metafísico; Kripke viene sosteniendo un esencialismo no epistémico desde los 60s. La idea de que la filosofía tiende a decir que lo que podemos conocer es todo lo que hay, o todo acerca de lo que se puede hablar objetivamente, existe y estoy completamente de acuerdo con Harman en que hay que atacarla. Pero se viene atacando hace muchos años; un ejemplo explícito es Davidson en Indeterminism and antirealism, pero la tendencia es anterior.

Para finalizar, el último párrafo es simplemente estúpido. La matemática, por lo menos, nunca trabaja a través de la catalogación exacta de propiedades y cualidades. Simplemente porque es imposible en la mayoría de los casos, por los teoremas de incompletitud de Gödel. La matemática ya era harmaniana antes de que Harman naciera. Y yo me pregunto: ¿qué pasaría si los próximos quinientos años vieran una filosofía que no hace la distinción aberrante que hace Harman entre “artes” y “ciencias duras”? Una filosofía que deja libres a los objetos, a los conceptos y a los métodos. Notar que Latour y Putnam ya se propusieron esto, y en gran medida creo que podemos confiar en que lo lograron. Pero Harman no tiene nada que aportar a esta historia triunfal lamentablemente.


[^1]: Graham Harman, [“Descubrir objetos nuevos es más importante que eliminar objetos viejos”](https://revistaluthor.com.ar/103.pdf).

[^2]: En Deleuze-Guatari y DeLanda aparece este cambio de dirección con los llamados “ensamblados”, que no se determinan por lo que contienen sino por los otros ensamblados en los que eligen incluirse.

[^3]: Notar de paso que críticas al reduccionismo ontológico, llamados al pluralismo ontológico incluso, existen hace mucho, y mucho más sofisticadas que esta. El locus clásico es el principio de tolerancia de Carnap. Para él nadie puede determinar racionalmente qué tipo de objetos pueblan el mundo. Quine, sin embargo, lo contradijo al sostener que la distinción entre preguntas internas (las que sí se pueden responder) y externas (metafísicas reductivas) de Carnap colapsa con la distinción analítico-sintético que él rechaza (verdad por significado contra verdad por hecho), y que por lo tanto preguntas sobre qué es y qué no deben ser tratadas a la par de preguntas más normales. Plantea, de todas maneras, que en última instancia la ontología queda indeterminada en su tesis del relativismo ontológico, y que, en cualquier caso, la referencia de nuestros términos singulares es inescrutable más allá de toda teorización. Putnam en sus escritos de los 80 sostiene y refuerza esta última tesis bajo la hipótesis de un marco de teorización en el que buscamos posicionarnos desde el punto de vista de Dios (que asocia tanto al realismo metafísico como al antirrealismo relativista), haciendo colapsar la pretensión de ese punto de vista. Su conclusión es sostener una noción de verdad objetiva (a la que hacemos referencia pero que no pretendemos capturar), si bien conceptualmente indeterminada. (En paralelo Davidson rechaza la noción de referencia como innecesaria, haciendo un punto similar.) El pluralismo conceptual de Putnam 1980 parece lo más cercano a la posición de Harman en esta parte, pero notar la diferencia: mientras para Harman encontrar un punto medio entre la reducción hacia abajo y la reducción hacia arriba es despojarnos de toda arma conceptual (todo “método”, como lo llama) para hacernos entrar en el terreno imposible de los “contramétodos” como única garantía para asegurar el falibilismo en todo el camino, Putnam nos llama a abrazar la proliferación de conceptos (y de los métodos para producir enunciados sobre el mundo que traen consigo) sin dejar nunca de tener en mente, y justamente por, que ninguno trae una garantía exclusiva a priori de producir verdad de manera privilegiada.

    Carnap es *Semantics, empiricism, ontology*. Quine es *On what there is*, *Two dogmas of empiricism* y *Ontological relativity*. Putnam es *Reason, truth and history* y *Realism with a human face*.

[^4]: Ver *Naming and necessity* de Kripke y *The meaning of ‘meaning’* de Putnam.
:::

<!-- Imported from https://medium.com/@juandodyk/comentario-sobre-harman-e062a278f2a9 -->
