---
title: "El cartismo cultural"
description: "Artículo escrito con José Duarte Penayo y publicado en el Suplemento Cultural del diario ABC Color, 18 de Septiembre de 2016."
date: 2016-09-18
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

Presentado oficialmente como «prestigioso conferencista e historiador», el bioquímico Fernando Griffith fue designado el pasado viernes 9 de septiembre como nuevo secretario de Cultura. Dueño de la fundación Paraguay Poderoso y asesor local en liderazgo de la fundación de Jonh Maxwell (gurú estrella del gobierno en la «capacitación» de la burocracia estatal a partir de una mezcla de autoayuda y espiritualidad pseudoevangélica), el nuevo funcionario asume sus funciones con un claro propósito: «recuperar la identidad de nación grande y próspera que tenía en el siglo XIX y volver a ser ejemplo para todo el mundo» (http://www.ip.gov.py/ip/?p=117102).

Sin pretender aventurar el futuro de su gestión como funcionario de Estado, en lo que sigue proponemos un análisis de algunos elementos de su particular visión del mundo, signada por un abanico de ideas que van desde el uso ideológico de las neurociencias, pasando por una interpretación de la supuesta supremacía cultural guaraní, hasta una lectura política no menos clara de la realidad social paraguaya.

## Reduccionismo biologicista y conflicto social como enfermedad: Griffith y el neurocartismo motivacional

Griffith vende, a través de su fundación y en los contratos que arranca al Estado, la idea de que es posible «reconstruir» el Paraguay cambiando las actitudes individuales de sus ciudadanos, dejando aflorar la «cultura guaraní» latente pero reprimida por el «fracaso». Hay tres elementos en la estructura argumental de su discurso que merecen ser destacados: la apelación ubicua a pseudosaberes disfrazados de ciencia como justificación última de sus juicios éticos y políticos; la idea de que fenómenos sociales complejos como la pobreza y la corrupción son síntomas de una enfermedad de la que los individuos deben curarse; y un optimismo ingenuo o perverso, según el cual los resultados positivos del modelo agroexportador redundan, aunque sea simbólicamente, en beneficios para todos.

En sus vídeos, el ministro de Cultura usa la biología y la neurociencia para avanzar su posición ideológica, como si la sola mención de dichas ciencias fuera legitimación suficiente. Así, habla de las «raíces biológicas» de los paraguayos, de las «tres moléculas del éxito» y de la necesidad de la expresión artística en el ser humano como «parte de su biología». Estas glosas, a pesar de carecer de sustancia y de un mínimo rigor científico, no cumplen un rol meramente decorativo; no son solo un recurso argumentativo burdo. Griffith cree y sostiene una versión rústica pero extrema del reduccionismo biológico: dice en uno de sus vídeos que «todo lo social: la historia, la sociología, la psicología, todo eso, son simplemente actos biológicos, son manifestaciones biológicas del ser humano».

Más allá de las críticas que merece ese pensamiento, y del peligro autoritario que encierra en tanto negación de la disputa política democrática, el reduccionismo tiene un corolario que es pertinente destacar. Griffith, al sostener que lo social es un fenómeno biológico, es decir, que responde a «leyes naturales» (se sustenta en mecanismos pre-políticos o pre-estatales de autorregulación), no hace otra cosa que reproducir una forma de naturalismo social. Ese sistema de pensamiento, cuyo origen data del siglo XIX pero perdura en la teoría económica del siglo XX, es, según Karl Polanyi, el sustrato ideológico del fundamentalismo de mercado, propugnado por las derechas latinoamericanas. Hay entonces ahí un punto de sintonía entre el liberalismo económico privatizador de Cartes y lo que a primera vista no parece más que un exceso de atribuciones del bioquímico devenido historiador Griffith: la invocación espuria de la ciencia usada una vez más como mecanismo de legitimación de la derecha.

Ese exceso se pone de manifiesto también cuando expone, en uno de sus vídeos, las características de las personas que fracasan y lo hace, según dice, «usando las neurociencias como base». Explica que la pobreza y la quiebra de una empresa son fracasos, y que estos ocurren si las personas no reconocen sus errores y sus responsabilidades, si se quejan y si se victimizan. Lo que podría ser consecuencia de políticas económicas contractivas o regresivas es reducido a un problema de quien sale perdiendo, único responsable; la protesta, se afirma, solo profundizaría su fracaso. En otro lado, Griffith afirma que el mal que aqueja a los paraguayos es una enfermedad –el desorden– cuyo agente causal es un desbalance entre hormonas (cortisol y oxitocina). Entre sus consecuencias señala la corrupción y la pobreza; por el contrario, un rasgo que destaca en los paraguayos del siglo XIX –previos a la enfermedad– es la obediencia. El desorden y, antes, el conflicto, son tratados como enfermedad; ser obedientes y aceptar lo que nos toca es salud.

La sola mención de la neurociencia (porque no se hace referencia a ningún estudio concreto que respalde las afirmaciones) pretende servir, con esto, de clausura a un debate que atañe al rol del individuo en la sociedad y lo que se debe tomar como justo por sus miembros. Este desatino excede a Griffith: circulan discursos moralizantes de neurocientíficos y sus divulgadores (algunos, incluso, con credenciales académicas legítimas) que intervienen en discusiones sobre lo colectivo desde una perspectiva que se pretende iluminada. Tampoco termina en Griffith la vinculación entre neurociencia y gobiernos de (centro-)derecha: hace poco, el neurólogo Facundo Manes fue incorporado al gobierno del Pro argentino.

Otro elemento del pensamiento de Griffith es su optimismo nacionalista. El Paraguay, según dice, es un país «en reconstrucción»: promoviendo la cultura guaraní y curando la «enfermedad» del desorden, el Paraguay volvería a ser el país con un alto nivel de desarrollo (para los estándares de la época) que fue en el siglo XIX, antes de la Guerra Grande. No hacen falta políticas de desarrollo, no hace falta reestructurar la matriz productiva, y el cambio abismal en los factores externos (las cadenas globales de valor, el movimiento libre de capitales) no juega ningún papel en la narrativa motivacional del nuevo ministro. Este optimismo ingenuo y alegre tiene sin embargo un costado perverso. Griffith llama a reconocer el progreso nacional, ese proceso de reconstrucción que milita, en indicadores como la cantidad de toneladas de soja o de carne exportadas. Cuestionar la renta extraordinaria que extrae el capital de esos negocios sería, según esta lógica, ir en contra del éxito de la nación.

## La supremacía de la cultura guaraní

En otro de sus vídeos (Paraguayos), Griffith sostiene la tesis de que el pueblo paraguayo es multirracial pero unicultural. Refuerza su idea afirmando que «no hay rastros de otras culturas en la identidad guaraní», pero sí rasgos «genéticos» de varias «razas» (sic). De este modo, la precariedad intelectual del ministro de Cultura se hace patente cuando confunde, de manera tragicómica, estereotipos culturales con supuestas características naturales de otros pueblos (los paraguayos tenemos «la determinación y el carácter de los vascos», «la capacidad de trabajar de los catalanes», «el orden y el ingenio alemán», «el amor por el arte, el estilo y el diseño de los italianos», «la capacidad de comerciar de los libaneses», etcétera).

Lo que en principio se negaba, es decir, la presencia de otras culturas en el «ser nacional», reaparece como cualidades tomadas en préstamo por medio de algún misterioso mecanismo no explicitado. Sin embargo, una correcta atención al «pensamiento» de Griffith esclarece la aparente incoherencia de su discurso: las cualidades incorporadas de otros pueblos no son en realidad cualidades culturales, sino sustratos genéticos. No se subsumen, «hegelianamente», determinaciones del espíritu, sino bancos genéticos provistos de «potencialidades actitudinales». Así, para el encargado de las políticas culturales del Paraguay, la cultura no existe como tal: es un epifenómeno de determinaciones biológicas. No hace mención a una historia, ni mucho menos da cuenta de procesos de construcción colectiva. Lejos de responder a una dinámica de apropiaciones y reapropiaciones que involucre la memoria, el conflicto y la participación de las instituciones, para Griffith la cultura es algo que está ahí desde siempre, un hecho natural al que hay que dejar fluir. Como al libre mercado, no deben ponerse trabas a la grandeza de nuestro acervo cultural; a lo sumo, presentarlo, tal cual es, en los prestigiosos ciclos de conferencias y demás aquelarres que suelen reunir a nuestra impresentable intelligentsia local.

Esta apelación biologicista a lo «natural», a «lo genético» y a la «raza humana» –categoría en desuso por lo menos desde mediados del siglo XX– como sustrato de la identidad, puede sugerir alguna adhesión al discurso nazi. Sin embargo, creemos que el núcleo de su discurso es otro: un supremacismo guaraní de connotaciones mágicas, por momentos delirante, por momentos enigmático (nunca se ha traducido en un éxito expansionista), pero que en todo caso se conjuga perfectamente con el imaginario liberal del individualismo y el culto al mérito.

Es en este sentido que debe entenderse la tesis implícita del secretario de Cultura de que la «cultura guaraní» puede ser considerada como superior a la «raza aria» puesto que la primera no necesita holocaustos para aplastar y disolver al resto. Es tan superior que no le hace asco a la «mezcla». En los términos de Roberto Esposito, ni siquiera necesita de «dispositivos inmunitarios» para conservar su pureza genotípica y fenotípica, y eso porque no existe en el universo «cuerpo extraño» capaz de amenazarla. Por el contrario: el ser de lo extraño se encuentra consigo mismo cuando ingresa a la unidad cultural guaraní. La «cultura guaraní» es, así, inalterable e in-degenerable. Es una fuerza vital que, apenas entra en contacto con otras «razas», las disuelve en su particularidad, alimentándose de ellas sin ningún riesgo de contaminación.

De cualquier modo, siguiendo el hilo argumental de Griffith, podemos entender que el supremacismo guaraní constituye una suerte de «nazismo superior y renovado», sin miedo a la mezcla, sin necesidad del gueto, casi universal pero siempre bajo la lógica de la incorporación y disolución del otro, de la destrucción de su particularidad en la unidad cultural guaraní (que, recordemos, admite «razas», pero no otras culturas). Por ello, es un supremacismo más parecido al de los «American values» (libertad negativa, consumo, meritocracia) que al del racismo nazi. La superioridad se ve en que convierte al otro, lo fagocita y lo homogeneiza, no en que lo elimina. No se elimina al «cuerpo extraño»; se lo incorpora y se diluye su otredad.

## Un orador motivacional para un gobierno deprimido

Si la Dra. Causarano fue necesaria para dar prestigio a un presidente que creía que las políticas culturales consistían en recuperar el Jardín de la Cerveza, hoy el escenario es otro (como señala Sergio Cáceres Mercado en un reciente artículo publicado en el diario Última Hora, «El gobierno de Cartes va hacia su franca decadencia en esta segunda mitad de su mandato»). En este momento de ostensible debilidad política del gobierno, marcado por la agonía del proyecto reeleccionista, la fractura del partido oficialista, los ocho militares asesinados por la narcoguerrilla y un nivel de desaprobación ciudadana de más del 80%, más que prestigio lo que se necesita es una inyección ilimitada de motivación. Ya no reconocimiento, crédito y reputación, sino estímulo, impulso y entusiasmo. Griffith es aquel que viene para dar un abrazo y decir que todo va estar bien, con la voz afectada de la falsificación histórica, el delirio biologicista y la venta de humo profesionalizada, revestidos todos con los honores del rango ministerial.

Sin embargo, Griffith no es solo el líder motivacional que necesita el gobierno en este momento de debilidad. Sus teorías –un cóctel de confusión, extravagancia y desvarío– podrían además proveer al gobierno de un relato, de una narrativa que le permita delinear una identidad ideológica más clara. En ese sentido, no se debe perder de vista la sintonía del discurso de autoayuda con todo orden neoliberal (por ejemplo, en la justificación positiva de la pérdida de derechos laborales y la supuesta conquista de una mayor libertad y autonomía individual), así como las condiciones óptimas que este último proporciona a su difusión. Si algo no debe ser subestimado es la audacia de la demencia, puesto que en determinados momentos puede expresar una verdad histórica, en este caso la de la derecha paraguaya y sus tópicos favoritos: el llamado a un optimismo nacionalista que no admite cuestionamientos al poder, la visión de la desobediencia como enfermedad, la queja y la victimización como supuestas causas del fracaso personal. El poder no siempre es el lugar del ocultamiento y la mentira, sino, de manera mucho más fundamental, el de la enunciación de sus propias verdades y aspiraciones.

[*Link al artículo.*](http://www.abc.com.py/edicion-impresa/suplementos/cultural/el-cartismo-cultural-1519619.html)
