---
title: "Violencia, justicia y limitaciones de una agenda"
date: 2016-11-21
date-format: "MMMM D, YYYY"
canonical-url: "https://juandodyk.github.io/posts/2016-11-21-violencia-justicia-y-limitaciones-de-una-agenda/"
---

::: {lang="es"}
Quiero hacer una reflexión sobre la violencia contra las mujeres y los límites de una agenda que busque erradicarla.

Parto, por supuesto, del texto que publicó Carolina Aguirre ayer en la Revista de La Nación. Hay muchas cosas muy valiosas que consigue. Una, mostrar a las mujeres cómo funciona el mecanismo: en las extorsiones del novio, la normalización del psiquiatra, sus propias dudas (¿estoy loca?, ¿seré yo la mala?). En eso puede ser liberador. Dos, menciona explícitamente la relevancia de un conjunto de recursos en la salvación, por decirlo de alguna manera, de la víctima. Cuando cuenta que el novio casi la mata y ella pudo tomarse un taxi e ir a un hotel dice: eso lo pudo hacer porque tenía plata. Me quiero centrar en ese punto.

Mi mamá, que es maestra en una escuela de villa, para decirlo fácil, en Avellaneda, contó una historia en el almuerzo. La reproduzco sin muchas precisiones. Aviso: no pretendo hacer periodismo. Esto es verdad, al menos en la medida en la que lo reproduzco bien, pero sólo lo cuento con fines ilustrativos. En la escuela tienen a un nene y sospechaban que el padre le pegaba; a él y también a la madre. La madre, una chica peruana que tendrá 25 años, siempre lo negó. Un día cayó a la escuela visiblemente golpeada. Andaba cerca con el marido, él comenzó a pegarle muy fuerte, ella huyó y se refugió en la escuela. No le quedó otra que “confesar” lo que le había pasado. Las asistentes sociales (o psicólogas, no sé) que trabajan con mi mamá (mi mamá no estaba; justo estaba de vacaciones) la convencieron de hacer la denuncia. La chica no trabaja; vive con el marido, un tipo mucho mayor que ella, un gordo enorme, también peruano. Ella no sabe viajar en colectivo, dice. No tenía nada encima. Ni una moneda, ni el teléfono de un familiar.

Las compañeras de mi mamá decidieron hacerse cargo. La llevaron a la comisaría de la mujer. Ahí le tomaron la denuncia y le dieron un papel como constancia. ¿Y qué hace con eso? ¿Vuelve a la casa? Le dijeron que vayan al servicio local (una institución municipal) para que vean qué hacer con el hijo (la idea era mandarlo a una guardería donde viven mujeres víctimas de violencia, algo así). Y a ella la mandaron a una suerte de juzgado descentralizado. En ese punto la inspectora (la autoridad sobre las compañeras de mi mamá) les dijo que no hagan nada más, que la dejaran ir con esas indicaciones. Ellas sabían que la chica no iba a poder ir a esos lugares por sus propios medios. Lo único que podía hacer por sí misma era volver a su casa con su marido. Entonces la acompañaron.

En el servicio local creo que las atendieron bien, y el nene al final terminó en el lugar que mencioné. Cuando fueron a la justicia las atendieron de urgencia a pesar de que había paro. Les dijeron que la denuncia iba a ir a sorteo. Había dos opciones. Si caía en el juzgado número 1, la jueza no iba a hacer nada con el caso, les aseguró en la cara la persona que las atendió. Si caía en el juzgado número 2, les iba a tocar una jueza que las compañeras de mi mamá conocían, y que seguramente iba a ayudarla a -al menos, en lo inmediato- sacar sus cosas de la casa como para poder irse a lo de un familiar. Se hizo el sorteo y les tocó el juzgado número 1. Mala suerte. Aunque no del todo: las trabajadoras sociales vieron a la jueza 2, que había salido a un patio a fumar un cigarrillo. Como la conocían, la saludaron, le contaron la situación y le pidieron ayuda. Dijo que iba a llamar al juzgado 1, el que les tocó, para que hicieran algo. Y sobre lo inmediato les dio una orden para que vayan a una comisaría y que un patrullero las acompañe a la casa de la chica y le permita sacar sus cosas. La jueza les dijo que no la acompañaran más a la chica, que el problema estaba resuelto. Ellas sabían que no podían dejarla sola.

Fueron a la comisaría. Si bien había un patrullero en la puerta, los policías les dijeron que no podían usarlo porque andaba mal. Tenían que esperar a que volviera alguno de los que andaban dando vueltas por la calle. Después de una hora de insistencia de las trabajadoras sociales, los policías accedieron a llevarlas con el patrullero que estaba ahí. Que no tenía ningún problema, claro. Leyeron la orden de la jueza y dijeron “ah pero no se jugó la jueza: no es una orden de allanamiento, así que sólo podemos entrar si está el marido y nos deja pasar; y sólo nos podemos llevar las cosas que él acepte entregarle a la mujer”. Así y todo fueron. El marido no estaba en la casa. Esperaron a la chica mientras intentó, desde el techo de la casa de un vecino, entrar a su casa por un hueco. No pudo.

La llevaron a la casa de sus suegros, que vivían cerca del lugar. Sí, de los suegros, los padres del marido golpeador. La chica se quiso quedar, aunque las compañeras de mi mamá le insistieron en que vaya con su propia familia. No pudieron convencerla y la dejaron ahí. Los directivos de la escuela no aceptaron seguir el caso. “Lo lamento”, dijo la directora. La chica tenía que ir a no sé dónde dentro de los siete días para que dejen constancia de los golpes que había recibido y avance la denuncia. No fue. A la semana siguiente ella y el nene volvieron a la casa. Hoy la chica sigue con el marido.

Quiero quedarme con algo de la historia. El Estado fue deficiente (tanto la policía como el poder judicial), y quiero mostrarlo con todos sus grises, pero no me quiero centrar en eso. Las trabajadoras sociales también fueron el Estado en esa historia; ahí hay un margen para matizar un poco. Lo que quiero destacar es la falta de recursos de esta chica anónima. Su total falta de independencia. Es un caso quizás extremo. Pero en la escuela de mi mamá hay otros casos de mujeres que hasta se “empoderan”, denuncian al marido, consiguen que éste no pueda acercarse a ellas a menos de tantos metros, y sin embargo al tiempo vuelven con él. Mi mamá contó de una mujer que después de vivir todo eso, un año después, “descubrió” que estaba embarazada de 28 semanas (7 meses). El padre era el marido, que tenía orden judicial de no acercarse a ella. Cuando se enteró de esto la asistente social se lo contó a la psicóloga del servicio local, con la que la mujer se estaba atendiendo. La psicóloga se sorprendió: la mujer lo había ocultado. Es que la dependencia puede ser de todo tipo; quizás en primer lugar económica. Pero también cabe imaginarse lo difícil y poco efectivo que puede ser para la mujer llamar al 911 cada vez que se le acerca el marido, quizás con, por lo menos aparente, buena voluntad, y alguna cosa que ofrecerle a ella y a sus hijos. La justicia (como es hoy) sólo puede llegar hasta cierto punto en ese caso, incluso cuando funciona bien.

Me quiero centrar en esto. En la limitación que tiene (hoy) el Estado, y la sociedad, ante casos así. ¿Qué puede, o qué debe, hacer el Estado frente a una mujer que depende económicamente de su marido, que no tiene una vida por fuera de ese hogar con ese hombre, que no tiene amigos, que no sabe tomarse un colectivo o no tiene una tarjeta Sube o ni siquiera tiene documento? Hay un punto en el que la justicia, creo, no se logra sólo encarcelando a los malos, o poniéndoles un cerco. La verdadera justicia, incluso frente a algo que aprendimos a pensar como algo criminal, no termina ahí, en darle, en el mejor de los casos, el derecho de tener la casa para ella y sus hijos, de aplicar el cerco, de ir a un psicólogo. Aparentemente (y aclaro que estoy haciendo una lectura superficial basada en un relato de sobremesa) a estas mujeres les falta algo más para poder realmente salir del infierno que viven. Les falta un horizonte de expectativas de una vida digna e independiente del tipo que les pega. Una red de contención a la que recurrir para hacer esa transición. Y en general recursos de todo tipo, empezando por guita, pero que no terminan ahí. Para que no exista esa injusticia creo que el Estado debería garantizar el acceso a esos recursos. No tengo la menor idea de cómo habría que instrumentar esto y cómo tendría que motorizarse la demanda desde la sociedad o desde la política. Y justamente esta dificultad es lo que quiero señalar.

El texto de Carolina Aguirre tiene un objetivo (que explica en parte por qué lo publicó, y dónde, etc) que me parece muy importante y es mostrar que estas cosas te pueden pasar (si sos mujer) incluso si tenés todos estos recursos de los que estoy hablando. Dicho rápido: Aguirre tenía todo lo que estoy diciendo que les falta a estas mujeres que viven tan precariamente, y sin embargo lo padeció, y casi termina muerta. Entonces: no es una cosa de pobres, ni es simplemente “falta educación” (el novio de Aguirre se declaraba feminista militante). Y es difícil para todas. De todas maneras agrego: sí, pero si sos pobre es mucho peor.

Esto me lleva a mi último punto, quizás el más oscuro, pero que creo que es lo más importante que tengo para decir. Es que la muerte, en cierto sentido, es una bendición para armar una agenda frente a este problema y poner a la sociedad a militar eso. El “Ni Una Menos” -su nombre lo dice- surge como un reclamo ante las muertes. Busca ponerles un nombre -femicidios-, pedir justicia por eso, y, bueno, visibilizar y combatir con una agenda concreta todo el proceso de abuso y opresión que lleva a esa muerte, etc. Pero pensemos en el último caso resonante que motorizó una marcha: el asesinato de la chica marplatense. La indignación, y la demanda, era porque, para decirlo rápido, ni la sociedad ni el Estado habían cambiado ni un poco, desde la última marcha, como para evitar esa muerte. Parecía hasta equiparable a un atentado terrorista; es probable que más de una mujer lo haya racionalizado como un mensaje aleccionador contra el “empoderamiento” que estaba en proceso. Como una reacción de los hombres que vieron su poder amenazado. Es posible. Pero en lo concreto, en lo estrictamente relevante al caso, y con respecto al Estado: ¿qué había para reclamar? Justicia, claro. Y no está de más hacerlo, sobre todo sabiendo (ex post) las dificultades que están teniendo los familiares de la víctima en el proceso, que no sabemos si va a terminar con una condena, etc. Pero en cierto punto el Estado ya sabía lo que tenía que hacer: buscar a los tipos que la asesinaron, juzgarlos y meterlos presos. Al menos en lo formal el Estado ya tenía resuelto el problema de cómo dar justicia ahí.

Pensemos ahora en el caso de la chica anónima del relato de mi mamá. En cierto sentido es más concreto y más urgente que la muerte de la chica marplatense. El asesinato es un hecho que ya pasó, y que, como se suele decir, ya está en manos de la justicia (sobre la que habrá que hacer presión para que funcione, etc). Quizás la sociedad tendrá que aprender, porque no termina de tenerlo claro, que eso está categóricamente mal, que es 100% culpa de los asesinos, y que termina funcionando como un ataque sobre la libertad de todas las mujeres, etc. Sí. Pero insisto: en este sentido lo que está viviendo la chica sobre la que cuenta mi mamá es más concreto y más urgente. El infierno que está viviendo lo está viviendo hoy, y lo va a vivir mañana, y pasado mañana, posiblemente hasta ser asesinada. No estamos hablando de reparar de alguna manera algo que ya pasó, o de iniciar un cambio cultural para que nuestros hijos puedan vivir blablabla. Es más concreto y más urgente. Y sin embargo esta historia no se va a volver viral como la de la chica marplatense ni se va a llamar a una movilización al respecto. Porque no tenemos, ni la sociedad ni el Estado, mucha idea de qué hacer con esta chica peruana que no sabe viajar en colectivo y que dice que prefiere quedarse con los padres del que la golpea. A esto iba.

Es deprimente, pero la muerte termina siendo algo “bueno” para impulsar una agenda que apunte a resolver este problema y consiga movilizar a la sociedad. Porque cuando hay una muerte desaparece la complejidad de la voz de la víctima, de sus recursos, de lo que la sociedad está dispuesta o se siente capaz de proveerle. Nadie va a hacer nada para frenar el infierno que vive la chica anónima de la historia de mi mamá. Recién cuando sea asesinada vamos a poder saber quién es y poner su foto en una pancarta y salir a la calle a pedir justicia por ella. Recién cuando sea demasiado tarde.

Aclaro, finalmente: esto no es una crítica al “Ni Una Menos”. Al contrario. Quizás sí puede funcionar como una crítica a sus críticos. Los que dicen que se queda corto, que no es efectivo y qué sé yo. ¿Son concientes de las dificultades? Que funcione el movimiento Ni Una Menos es un mérito extraordinario, y se explica en parte, creo, por sus propias limitaciones. ¿Sabemos exactamente qué agenda tenemos que tratar de imponerle al Estado (y a nosotros mismos) para resolverle el problema a las mujeres de las historias que cuenta mi mamá? Yo creo que no. Que hay que empezar por algún lado, y se está haciendo, y hay que profundizar eso. Pero que hay un punto en el que no tenemos la respuesta, y es posible que no la tenga nadie. Un punto más allá del cual ninguna reforma progresista, ninguna reforma de género, puede avanzar.

Por último. Sí, puede ser un poco irresponsable de mi parte decir todas estas cosas sin dar precisiones, sin involucrarme. Sí. Pero es sólo una reflexión, algo que dije en un chat y me dijeron que escriba. Hagan lo que se les canta con esto.
:::

<!-- Imported from https://medium.com/@juandodyk/violencia-justicia-y-limitaciones-de-una-agenda-cb4f82849a56 -->
