---
title: "Errores de los estudiantes en la materia Matemática del CBC"
description: ""
date: 2012-10-21
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

Escribí un comentario sobre el artículo ["Errores, actitud y desempeño matemático del ingresante universitario"](http://dialnet.unirioja.es/servlet/articulo?codigo=4766896), de Dodera, Bender, Burroni y Lázaro. Lo hago sobre mi experiencia docente en el área de matemática del Ciclo Básico Común, UBA.

## Sobre los errores

Me gusta mucho la idea de estudiar los errores de los chicos. Esto por supuesto es parte del trabajo cotidiano ordinario de los profesores, cuando un alumno les muestra un ejercicio hecho entero o a medias o cuando corrigen un parcial. Los profesores rutinariamente trabajan sobre los errores de los chicos, tengan formación didáctica formal o no (como en mi caso), cuando tratan de determinar ‘qué quiso hacer’ el chico, ‘cuánto’ resolvió de un ejercicio dado (‘hasta dónde llegó’), si tuvo errores ‘de cuentas’, ‘de modelado’, ‘de procedimiento’, etc. La actividad de hacer inteligibles y conmensurables los errores, clasificarlos y valorarlos es algo que todo profesor hace, sin ningún conocimiento formal o sistemático, sin estándares ni método. (Es una actividad que, por supuesto, no es general, sino adecuada a la materia y a sus tipos de ejercicios; así es que los profesores hablan de ‘errores de modelado’ en ejercicios de optimización pero no en ejercicios de límites, y así resulta que no hay una categorización única y muti-propósito sino clasificaciones y valoraciones adecuadas.) Quizás sería interesante estudiar el trabajo no formalizado, no ‘científico’, no informado por ningún discurso metodológico que llevan a cabo los profesores sobre los errores de los chicos rutinariamente, como parte esencial e inseparable de su trabajo como profesores, en el aula o en las conversaciones entre ellos entre horas.

Doy un ejemplo para que se vea de qué estoy hablando.

Ayer me puse a corregir un parcial de análisis con Alicia. Un chico escribió soluciones para los cuatro ejercicios, que vistas por arriba parecían impecables, en el sentido de que seguían la forma (la sucesión de pasos) esperada, mostrando competencia conceptual y éxito en su aplicación en esos ejercicios particulares. Sin embargo, cuando me puse a mirar en detalle me encontré con que tres ejercicios tenían, cada uno, un muy pequeño error que los arruinaba por completo. Pasé de pensar que iba a sacar diez a pensar que quizás no llegaba al cuatro. Dos de esos tres errores eran (según mi análisis) el mismo: que el chico no sabía usar la regla de la cadena y derivaba f(g(x)) como f'(g(x)). Alicia me dijo que se debe penalizar fuerte el no saber derivar, y eso hice en uno de los ejercicios, que salvo la falta de una x en una derivada estaba perfecto, poniéndole Regular. Ahora bien, como vi un manejo conceptual excelente, y salvo por los tres pequeños errores, que eran por ignorancia de la regla de la cadena y por un cuadrado de binomio mal hecho, parecía que habría resuelto bien los cuatro ejercicios, me decidí a aprobarlo. Entonces acordé con Alicia en ponerle Bien-menos-menos en uno al que sólo le faltaba la regla de la cadena y Regular-menos-menos en el que tenía Regular, para que la nota llegue a un cuatro ajustado.

Con esto se ve lo metodológicamente delicado del análisis que hacemos de los errores, no orientado por ninguna metodología formal (ni Alicia ni yo estudiamos metodología de la enseñanza ni nada parecido hasta donde sé). Reflexivamente, pero sólo porque es parte del trabajo (es decir, sin ninguna intención, interés, creencia, concepción o competencia especial), y como parte rutinaria del trabajo (y no como, por ejemplo, una reflexión sobre cómo hacer las cosas mejor), hacemos un análisis de los errores de los chicos en el que tratamos de ver cuán profundos son (si son accidentales, conceptuales, de prodecimiento, etc.), cuán arraigados están (si se repiten), a qué forma general responden (e.g., ‘acá el error es que no sabe regla de la cadena’), cuán importantes son (cuán severamente debemos penalizarlos), etc. Y por supuesto que nuestra enseñanza está orientada por el análisis de los errores que hacemos, en tanto nuestro humilde objetivo es que aprueben los parciales, es decir, que sepan resolver sin errores, o con la menor cantidad y ‘mejor calidad’ de errores posibles, el tipo particular de ejercicios que se toman.

Cuando se dice que error es la práctica del alumno que no es válida desde el punto de vista de la institución hay que tener un cierto cuidado conceptual. Por un lado, hasta que ningún miembro competente señala el error, no sé si se puede hablar de error (no tiene que ser necesariamente un profesor; un chico puede señalar un error, o un observador apto). Quiero decir, los errores no son simplemente fallas a una norma; son cosas que no existen si no son producidas por medio de un trabajo que requiere competencia (que provee la institución) y, por decirlo de alguna manera, un montón de contexto (un ejercicio de la guía, un examen). Por otro lado, un miembro sólo puede ‘producir’ un error (señalarlo como error, identificar la norma que se está rompiendo) sobre la base de material que está hecho de tal manera que lo hace analizable como error. Si se me permite decirlo así, lo que se llama errores son prácticas que no son 100% válidas desde el punto de vista de la institución, pero son, por lo menos, 90% válidas.

Mi comentario, en resumen, es que los errores son mucho más que simplemente prácticas no válidas. La institución no determina solamente qué no es un error (qué cosas son válidas); también determina qué cosa sí es un error y, cuando lo hace, provee un análisis del mismo, que es bastante más que simplemente ‘esto está mal’.

## Sobre la conclusión del análisis de los errores

No me gusta mucho la categorización de Movshovitz-Hadar, Zaslavksy e Inbar que usaron. De hecho en las conclusiones ustedes dicen que costó usarla. Lo que sí me pareció interesante es la conclusión ‘los errores son mayormente errores sistemáticos de procedimiento’. Que los chicos, por ejemplo, tengan problemas evaluando polinomios es algo que yo noté (informalmente, sin estadísticas, obvio) más en general: los chicos no tienen claro el concepto de reemplazar *x* en una expresión, por más obvio que parezca. Creo que es difícil entender que una función es una cosa que para un *x* devuelve un *y* (aunque pareciera que esto es la definición misma de función, y que si uno no entiende esto no puede hacer nada con funciones). Y es que las funciones para los chicos siempre existen en ejercicios específicos, como ‘calcular raíces’ o ‘graficar’, y no como entidades separables, independientes. Por ejemplo, vi que chicos que saben graficar cuadráticas no se dan cuenta de que pueden hacer esto, usar esto como recurso, si aparece una cuadrática en medio de otro ejercicio (e.g., saber si una cuadrática es siempre positiva para, e.g., hallar el dominio de una función dada por una fórmula, como log(x^2-x+1); siento que los mareo si para graficar log(x^2-x+1) grafico x^2-x+1; creo que los marea que un gráfico sea un recurso, que podemos usar o no, en vez de una actividad que se pide hacer, sin sentido si no está la orden ‘graficá’). Pero entiendo que está bien esto, que es lógico, porque, como dijo Wittgenstein hasta el cansancio, ningún concepto tiene un sentido más allá de su uso. Sería un error pensar que ‘saber lo que es una función’ o ‘saber resolver cuadráticas’ es o debería ser lo mismo que saber hacer *cualquier* cosa con funciones o cuadráticas. Me parece que tiene sentido (aunque es algo no obvio, y de hecho un resultado sorprendente y muy interesante) que los chicos no sepan ubicar puntos racionales en la recta, incluso si saben sumar y comparar racionales. Nadie les enseñó a hacer eso, y evidentemente no tienen por qué saberlo, incluso si saben hacer otras cosas con esos números. Por eso me parece muy buena la idea de la prueba diagnóstica y el análisis de los errores, porque se ven todas estas cosas que uno cree que los chicos saben hacer, porque ‘cómo no las van a saber, si saben tal otra cosa’, pero no las saben. (Ya sé que a ustedes les interesa más el hecho de que algunas cosas se las enseñaron en la escuela pero mal; a mí me intrigan las pequeñas cosas no obvias del aprendizaje de la matemática.)

(Otro ejemplo: una alumna sabe hacer el estudio completo de una función y sabe graficarla, pero noto que le cuesta muchísimo saber a partir del gráfico cuántas soluciones tiene la ecuación f(x) = k, cosa que ‘debería ser obvia’ sabiendo el concepto de función y teniendo el gráfico de f.)

## Sobre los conocimientos previos

Otra cosa que me gustó mucho fue el estudio de la correlación entre el desempeño en la prueba diagnóstica y el primer parcial. Noté que hay ciertas cosas (no sé exactamente qué cosas) que se asume que los chicos saben, y que no se enseñan como parte normal de las clases (digamos, no están en el programa). Hay cosas muy sutiles que los chicos pueden no saber hacer, y que nosotros quizás ni siquiera sabemos que se enseñan; no se nos ocurre que alguien en algún momento tiene que habérselas enseñado para que las sepan (ese alguien pudo haber sido ser el mismo chico, obvio). (Lo que quiero decir es que podría pasar que alguien sepa hacer X pero no Y, mientras que uno pensaría que si sabés X también tenés que saber Y; la conclusión es que evidentemente Y se aprende, que no es lo mismo que X, y a eso me refiero cuando digo que Y se enseña. Decir ‘pero Y se deduce lógicamente de X’, o decir ‘el problema es que al chico le falta pensamiento lógico-deductivo’, o ‘es que el chico no sabe X de verdad, sólo superficialmente, o sólo mecánicamente’ o algo así por supuesto no sirve de nada, porque la mayoría de la matemática se deduce de ZFC lógicamente y sin embargo no aprendemos toda esa matemática ni bien nos enseñan ZFC.) Es interesante identificar esas cosas. También es interesante ver qué les pasa a los chicos que no las saben. Dicen que hay chicos que recursan y después aprueban. Me puedo imaginar a un chico que no tuvo los ‘conocimientos previos’ en su primera cursada, y por eso no aprobó, pero que de alguna manera para la segunda logró aprenderlos (no tengo idea cómo). Quizás sería interesante hacer la prueba diagnóstica en varios momentos de la cursada para ver qué cosas van aprendiendo los chicos (o qué errores sistemáticos se les van corrigiendo) y qué cosas no.
