---
title: "Nuevo libro de Latour"
date: 2015-11-26
date-format: "MMMM D, YYYY"
canonical-url: "https://juandodyk.github.io/posts/2015-11-26-nuevo-libro-de-latour/"
---

::: {lang="es"}
Hace un mes [esto fue escrito en Septiembre, 2013] se publicó la traducción al inglés del último libro de Bruno Latour, *An Inquiry Into Modes of Existence* (publicado en francés en septiembre del año pasado), traducción de Catherine Porter. En Internet está colgado el primer capítulo y el índice [http://www.bruno-latour.fr/node/252](http://www.bruno-latour.fr/node/252)

Leí el primer capítulo. Parece un libro muy general, que sigue la línea de *Science in action* y *Reassembling the social*: tratados más o menos sistemáticos de teoría del actor-red, cada vez más ampliada (se podría poner *Irreductions* como predecesor en esta serie). ¿Qué se puede agregar a RTS? En palabras de Latour, la idea es hacer una antropología positiva de los Modernos, quienes, como recuerda, nunca fueron modernos, pero eso es sólo una definición negativa. El camino es estudiar los varios tipos de condiciones de felicidad de los varios tipos de producción de verdad, los varios *regímenes de enunciación* (científica, legal, religiosa, etc). Esta es la manera semiótica de decirlo; otra manera, mezcla de Simondon y William James, equivalente para Latour, es estudiar los diversos *modos de existencia* de las cosas que pueblan el mundo de los modernos, que recordemos son como “adverbios” directamente accesibles a la experiencia. El tema no es aprender a hablar *sobre* la ciencia, o *sobre* la ley, o *sobre* la religión, sino aprender lo que es hablar *científicamente*, *legalmente*, *religiosamente*. Capturar la “esencia” de la ciencia, la ley, la religión, no como *dominios* sino como *maneras* específicas de establecer relaciones entre elementos heterogéneos.

¿Cómo se engancha esto con la “vieja” teoría del actor-red? La historia es más o menos así: el concepto de red, o de *actor-red*, sirve para hablar sobre las cosas mostrando una dualidad entre *actor* (o “actante”) y *red*, “efecto de red”, “asociación” entre entidades que uno no reconocería como que son la cosa, o que son parte de la cosa. (Dualidad como la dualidad onda/partícula: las cosas se pueden ver alternativamente como actores o como redes; como entidades (Quine) o como ficciones ([Yablo](http://www.mit.edu/~yablo/apex.html)).) La idea es no negar la *realidad* de las cosas, pero verla como *efecto de relaciones*. Las relaciones, las conexiones, las asociaciones, las mediaciones están primero, no son relaciones entre cosas fijas sino que hacen que las cosas que relacionan existan. Bajando a algo un poco más concreto, tenemos por un lado la sociología de la ciencia que, mal pero comúnmente entendida, estudia los “factores sociales” que intervienen en la ciencia. O la sociología de la denuncia que muestra que la ciencia o el arte, el conocimiento, la “realidad” o el gusto artístico, son “sociales”, están “socialmente construidos”. Plantean la ciencia/el arte, por un lado, y la sociedad, por otro, como dominios, como cosas fijas, y estudian las relaciones causales entre ambos, mostrando que lo que es supuestamente puramente científico, o puramente artístico, tiene un “componente” o una “causa” social, donde “lo social” es un material, un tipo de cosa. Latour dice: *la sociedad no cuenta como recurso explicativo*. La sociedad no es algo que puede explicar otra cosa; es algo que hay que explicar por las otras cosas. Sociedad entendida como relaciones, y no como la cosa de la que hablan los sociólogos, como dominio sui generis que se puede estudiar con métodos específicos, etc. No hay un dominio primitivo, puramente social, puramente humano, de “convenciones”, “ritos”, “afinidades”, etc, que convive con el resto de los dominios definidos por los modernos, la Ciencia, el Arte, la Ley, el Mercado, etc. La idea es no separar a priori entre dominios separados (mucho menos para después denunciar que la separación es ilusoria) sino mostrar el duro y eterno *trabajo* de *asociaciones* y de *asignación de identidades* al que deben dedicarse los actores para poder usar los apelativos de científico, artístico, legal, etc. Se abandonan así todas las distinciones a priori entre naturaleza y cultura, conocimiento científico y no científico, experiencia estética y no estética, etc. Lo que dice Latour es, entonces: todo es social, todo es red (pero es un dictum vacío, una tautología); cada práctica, cada conexión, establece un tipo de construcción de realidad distinto: la ciencia a su manera, el arte a la suya, etc; pero la ciencia no está hecha de cosas científicas ni el arte de cosas artísticas, sino que tejen, cada una a su manera, lazos entre elementos de todo tipo. “Objective facts are not produced objectively, the same way milk is not produced ‘milkly’.” De esta manera, en el contexto de la teoría del actor-red, los dominios de los modernos se ven como tipos de asociaciones que entre todas hacen el entramado de nuestro mundo, es decir, de la sociedad o, mejor dicho, del “colectivo”. Nada queda afuera: conocimiento científico, personas, la “naturaleza”, objetos técnicos, obras de arte, códigos legales, todo es parte del colectivo, todo debe estar imbricado en alguna red para poder existir, red que lo conecta de mil maneras diferentes con mil cosas todas de distintos tipos pasando por mil lugares y mil tiempos diferentes.

Hasta acá todo me parece que viene bien. Con este espíritu venían estando escritos todos los libros anteriores de Latour, incluso los más abocados a “definir” algún tipo particular de régimen de verdad, a responder una pregunta “qué es”. Todo venía en la dirección de la pluralidad, de mostrar que hay muchas maneras de hacer las cosas, que nunca hay que cerrarse a conexiones inesperadas, que la sociología es problema de los actores, etc. Pero este nuevo libro parece que pretende hacer algo distinto. Cito la página web: ‘a research protocol has been developed that is very different from the actor-network theory. The question is no longer only to define “associations” and to follow networks in order to redefine the notion of “society” and “social” (as in “Reassembling the Social”) but to follow the different types of connectors that provide those networks with their specific tonalities. Those modes of extension, or modes of existence, account for the many differences between law, science, politics, and so on.’ En el texto esta bisagra, este punto donde el proyecto se despega de aquél de RTS, está, entiendo, exactamente en la página 37, en esos dos párrafos.

En el primer párrafo dice que lo que define una práctica es, para los actores, un “no sé qué”, y que es el trabajo del antropólogo dar una formulación precisa. En el segundo, que la red no basta, no es todo: hay que determinar los “valores” que circulan en la red.

Acá Latour me defrauda: da un paso atrás, me parece. La tarea de definir los “valores” parece una vuelta a Weber, el Weber que lleva directo a Merton. Se pierde la lección de Garfinkel (que está en Wittgenstein, en Heidegger, en Rorty, en Putnam): no hay una mejor formulación de ese “no sé qué”. La sociología tiene que contentarse con ser una teoría negativa, que termine justamente donde termina la red, donde algún actor hizo algún trabajo de definición, y no avanzar más.

Latour había ayudado, entre otros, a despegarnos de las definciones de ciencia, ya sea basadas en un “método científico” (ejemplo, el falsacionismo de Popper) o en ciertas “condiciones sociales” (las teorías de Merton o Bourdieu), encargados de diferenciar la construcción de teorías/creencias “racionales” de las demás, ya sea desde adentro o desde afuera. Latour (con muchos otros) nos enseñó que la ciencia no está hecha sólo de teoría, sino de infinidad de elementos heterogéneos, y que la sociedad no afecta o crea a la ciencia, sino que la ciencia crea sociedad, es en efecto “política hecha por otros medios” (así como “technology is society made durable”), por lo que la distinción entre adentro y afuera debe colapsar [el primer paso en esta dirección, medio chueco, lo dieron Bloor y Collins, al proponer estudiar la ciencia desde adentro pero sociológicamente]. Así como Baxandall y Svetlana Alpers nos enseñaron, con el arte, que la experiencia estética es un producto complicado de experiencias de muy diversos tipos (eg el estudio de la experiencia estética del Quattrocento de Baxandall) y que los artistas crean las condiciones sociales para la valoración y definición de su arte como arte y de ellos como artistas (eg el estudio de Rembrandt como empresario de Alpers); y que por lo tanto una definición, una demarcación, ya sea interna (como la de Kant) como externa (como la de Bourdieu) no sirve para entender el arte.

Ahora Latour dice: yo y mis amigos hicimos todos los trabajos de campo que hicieron falta. Con cada uno de los supuestos dominios modernos fuimos mostrando cómo las definiciones de los teóricos fallaban, una por una. Pero ya está, *ya terminamos*, ya hicimos suficiente trabajo de campo. Ahora podemos poner nosotros nuestras definiciones. La ciencia no es conocimiento falsable, o el bien que se comercializa en el campo científico. Ciencia es un tipo de conexión, que llamamos “referencia”, en la que información es transportada a través de una larga cadena de transformaciones. Con la religión lo mismo: no es creencia en una deidad, en un mundo invisible, o la formación de la identidad de un grupo (la definición durkheimiana; esto Latour lo llamaría política), sino un tipo de relación, muy parecida a lo que llamamos amor, en la que una persona se hace presente.

Pero, ¿qué pasó? ¿Qué hacen estas definiciones? ¿Para qué las queremos? ¿Cómo sabemos si están bien o están mal? En el contexto de la teoría del actor-red se pueden responder estas preguntas: uno estudia un actor-red particular y sigue las conexiones con elementos de todo tipo que lo hacen funcionar; uno ve que no toda conexión que se prueba funciona, que no todo da lo mismo, y se puede extraer (de las controversias que surgen y la manera en la que se cierran) la definición del modo en el que existe el actor-red en cuestión, es decir, el régimen de verdad en el que cuenta su historia, el “order of worth” propio con el que se justifica (a la Boltanski-Thevenot). Pero en este contexto de antropología filosófica tan general, en el que buscamos determinar los “valores” con los que se guían los modernos para construir su mundo, ¿podemos decir algo?, ¿queremos decir algo? ¿Por qué no basta con la teoría negativa de RTS?

Conclusión: no sé, tendré que leer el libro. Pero el sabor que me deja leer el primer capítulo es agridulce. No sé si Latour está dando un paso adelante o un paso atrás con esto.

PD: Ya está la traducción al español en librerías. No me esperaba que apareciera antes en español que en inglés. Parece que hay un público hispanoparlante.
:::

<!-- Imported from https://medium.com/@juandodyk/nuevo-libro-de-latour-3242fa088442 -->
